CHANGES.rst
mathics/builtin/numbers/calculus.py

This PR partially provides support for #46. By now, it just supports series on a single variable.

support for Normal[SeriesData[...]]

---

mathics/builtin/numbers/calculus.py

Add section description for Calculus functions

---

CHANGES.rst
mathics/builtin/numbers/calculus.py

this fixes a test in `Series`.

fix Series test

---

examples/symbolic_logic/gries_schneider/GS0.m

last tested on legacy Mathics, before Mathics was split up. Uploading for completeness.

Issue #96: missing file

---

mathics/builtin/arithmetic.py
mathics/builtin/inference.py

Fix bugs in assumptions-related messages

---

mathics/builtin/numbers/calculus.py

Bug fix from @oscarbenjamin.
Fix #98.

bug fix: N doesn't compute the real roots of an equation

---

mathics/core/atoms.py

Use `bit_length()` and `machine_precision`
These two items suggested by mmatera. 
I am not certain though if this fully addresses the concerns, so double check.

Use bit_length and machine precision

---

CHANGES.rst
mathics/core/atoms.py

Reverts Mathics3/mathics-core#106

Revert "fix N (Issue #103)"

---

.gitpod.yml

To test this:
https://gitpod.io/#https://github.com/TiagoCavalcante/mathics-core
We should add an easy-to-find mention to this, I recommend a badge in README.

Add .gitpod.yml

---

mathics/core/definitions.py
mathics/core/pattern.py
mathics/core/rules.py
mathics/core/symbols.py

Basically took some of what was in https://github.com/Mathics3/mathics-development-guide/pull/16
and included this as docstrings. Some of the text has been reworked a little.

Add some important class docstrings

---

mathics/builtin/datentime.py
mathics/builtin/inout.py
mathics/builtin/list/associations.py
mathics/builtin/list/eol.py
mathics/builtin/lists.py
mathics/builtin/patterns.py
mathics/builtin/quantities.py

From original:  associations should be primitives
@TiagoCavalcante, @rocky, this rebases PR#90 over the new changes.

Improve association - rebase PR#90

---

mathics/builtin/structure.py

Fix issue https://github.com/Mathics3/mathics-core/issues/201 changing argument of the function to list
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/207"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix behaviour of OrderedQ 

---

mathics/builtin/base.py
mathics/builtin/patterns.py
test/test_rules_patterns.py

Fixes issue #203
Also remove some duplicate imports
(After merge I'll update CHNAGES.rst - to do so now will just cause merge conflicts.)
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/208"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Tolerate head that is None in get_attributes

---

mathics/builtin/numbers/linalg.py
test/test_linalg.py

Sympy  has troubles inverting matrices whose elements are functions. This PR fix the issue.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/206"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fixing matrix inverse  (Issue #205)

---

mathics/core/pattern.py
test/test_rules_patterns.py

Fixes #202.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/212"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Covert tuple to list so we can use the method remove

---

mathics/builtin/assignments/internals.py
mathics/builtin/numbers/linalg.py
test/test_linalg.py

Just a couple of lines handles #210
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/213"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix issue #210

---

setup.py

So accept that.
I am trying to get out another docker release, so we may as well, use newer versions of everything. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/221"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Sympy 1.10 is out and it works on Mathics

---

mathics/builtin/matrices/constrmatrix.py
mathics/builtin/matrices/partmatrix.py
mathics/builtin/tensors.py

As in https://github.com/Mathics3/mathics-core/pull/215#pullrequestreview-915117546

Moved DiagonalMatrix and IdentityMatrix to group Matrices and Linear Algebra

---

CHANGES.rst
mathics/builtin/arithmetic.py
mathics/builtin/numbers/constants.py

Fixes #242
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/243"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Handling Overflow locally

---

mathics/builtin/assignments/assign_binaryop.py
mathics/builtin/assignments/assignment.py
mathics/builtin/assignments/types.py
mathics/builtin/atomic/atomic.py
mathics/builtin/atomic/numbers.py
mathics/builtin/atomic/symbols.py
mathics/builtin/compilation.py
mathics/builtin/datentime.py
mathics/builtin/list/constructing.py
mathics/builtin/matrices/constrmatrix.py
mathics/builtin/matrices/partmatrix.py
mathics/builtin/numbers/algebra.py
mathics/builtin/procedural.py
mathics/builtin/quantities.py
mathics/builtin/recurrence.py

* start out with imperative verb
* no leading capital (unless it is a name or abbreviation)
* no trailing period
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/251"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Make tense and form match in summary_text

---

.github/workflows/autoblack.yml
mathics/builtin/fileformats/htmlformat.py
mathics/builtin/fileformats/xmlformat.py
mathics/builtin/list/associations.py
mathics/builtin/list/constructing.py
mathics/builtin/list/eol.py
mathics/builtin/list/rearrange.py
mathics/builtin/lists.py
mathics/builtin/moments/basic.py
mathics/builtin/numbers/exptrig.py
mathics/builtin/numbers/randomnumbers.py
mathics/builtin/string/patterns.py

Here I completed more summary texts and docstrings. Also I moved some builtins to submodules where they seems to belong.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/255"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

more summary_texts

---

mathics/builtin/base.py
mathics/core/element.py
mathics/core/expression.py
mathics/core/rules.py
mathics/core/symbols.py
mathics/core/util.py
test/core/test_elements_properties.py

This is to give people some sense of what's up here. The useful properties aren't used yet.
Elsewhere I will provide a more full description of the observations, motivation, deficiencies and possible future direction.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/250"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

WIP - First cut elements properties

---

mathics/core/expression.py

See  specific notes in the file for comments.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/265"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Revise some expression comments

---

mathics/builtin/assignments/internals.py
mathics/core/atoms.py
mathics/core/symbols.py

some of these in fact fix bugs
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/272"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Misc flake8 caught things..

---

mathics/builtin/attributes.py
mathics/builtin/evaluation.py
mathics/builtin/functional.py

more summary texts...
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/274"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

More summaries 4

---

mathics/algorithm/parts.py
mathics/algorithm/series.py
mathics/builtin/arithmetic.py
mathics/builtin/assignments/internals.py
mathics/builtin/base.py
mathics/builtin/box/compilation.py
mathics/builtin/box/graphics.py
mathics/builtin/comparison.py
mathics/builtin/files_io/files.py
mathics/builtin/inference.py
mathics/builtin/list/associations.py
mathics/builtin/list/eol.py
mathics/builtin/lists.py
mathics/builtin/numbers/algebra.py
mathics/builtin/numbers/calculus.py
mathics/builtin/patterns.py
mathics/builtin/string/operations.py
mathics/core/evaluators.py
mathics/core/expression.py
mathics/core/subexpression.py
mathics/main.py
test/test_custom_boxconstruct.py

OK, this was less painful than what I expected.  The question now is if we do not introduce too much overhead by replacing the direct access to a property value by a function call...
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/277"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

removing __elements

---

mathics/builtin/comparison.py
mathics/builtin/logic.py
mathics/builtin/optimization.py
mathics/builtin/optiondoc.py
mathics/builtin/patterns.py
mathics/builtin/sparse.py
test/test_compare.py

adds summary texts in 
comparison.py
logic.py
optimization.py
optiondoc.py
patterns.py
sparse.py
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/276"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Summary text more5

---

mathics/builtin/box/graphics.py
mathics/builtin/distance/stringdata.py
mathics/builtin/files_io/files.py
mathics/builtin/files_io/filesystem.py
mathics/builtin/files_io/importexport.py
mathics/builtin/files_io/mainloop.py
mathics/builtin/intfns/combinatorial.py
mathics/builtin/intfns/divlike.py
mathics/builtin/intfns/recurrence.py

Here, I completed `distances`, `files_io`,  and `intfns`  documentation.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/261"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Summary text more2

---

CHANGES.rst
mathics/builtin/numbers/numbertheory.py
mathics/core/atoms.py

Every now and then I use Mathics as a hobby item. (That's why I was interested in it in the first place.)
Something I wanted in playing around with Mathics.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/286"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add EulerPhi and specialize Integer comparisons

---

mathics/builtin/assignments/internals.py
mathics/builtin/base.py
mathics/builtin/box/graphics.py
mathics/builtin/inference.py
mathics/builtin/patterns.py
mathics/core/atoms.py
mathics/core/element.py
mathics/core/expression.py

Following https://github.com/Mathics3/mathics-core/pull/290#issuecomment-1129348529, here I implemented the changes to make  `BoxConstruct`  inherits from BaseElement.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/292"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

BaseElement.apply_rules-> BaseElement.do_apply_rules

---

CHANGES.rst
mathics/algorithm/simplify.py
mathics/builtin/numbers/algebra.py
mathics/builtin/numbers/calculus.py
mathics/core/systemsymbols.py
test/test_algebra.py

This fixes #188.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/189"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Complexityfunction

---

mathics/builtin/base.py
mathics/builtin/fileformats/xmlformat.py
mathics/builtin/graphics.py
mathics/core/evaluation.py
mathics/core/parser/convert.py

These are random droplets amongst a sea of needed changes,. They happen to be some of the changes I made in the expression-interface-factor branch that I need to dumb down that I need before ListExpression can go on.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/304"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Miscelleanous to_expression/Expression separation and some leaf->element correction

---

mathics/core/expression.py

This simple and obvious change reduces `Timing[Do[F[a,a,a,a,a,a,a,a,a,a,a];,{1000}]][[1]]` from 0.426693 to 0.356115.
In the expression-interface-refactor branch where we do not have conversions in the `Expression()` constructor this is down to 0.236587 which is still a little but above the Mathics 4.0.0 value: 0.220522
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/312"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Remove redundant assigns in {eval,rest}_range

---

mathics/builtin/fileformats/xmlformat.py
mathics/builtin/lists.py
mathics/core/expression.py
mathics/core/list.py

First cut at ListExpression
Many things don't work though. See comment-out code for avenues to explore.
@mmatera @TiagoCavalcante Feel free to hack away at this. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/308"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

List expression lite

---

mathics/builtin/lists.py
mathics/core/list.py
test/builtin/test_assignment.py

The changes that I proposed to #325.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/331"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

List expression evaluation 2

---

mathics/builtin/distance/numeric.py
mathics/builtin/numbers/linalg.py
mathics/core/list.py

These were the remaining ListExpression items I didn't have the energy to go over in the first round. 
Here I also sort the builtin class names and move the Numeric Distance functions into Distance and Similarity measures as it is described and organized in https://reference.wolfram.com/language/guide/DistanceAndSimilarityMeasures.html
This change alone is big enough for its own PR.
In general a PR is no bigger than what I can tolerate in a single session that I have time for. I am also hoping that it also limits the amount of effort to double check this as well. 
To reduce confusion it may be useful to look at the 3 commits individually, especially commit 2 and then commit 3.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/339"><img …

Linalg refactor

---

mathics/builtin/graphics.py
mathics/builtin/numbers/algebra.py

This PR completes the documentation of the built-in modules and adds a pytest to check that new builtins are properly documented.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/341"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Complete Graphics and Algebra documentation and summary_tests.

---

mathics/algorithm/series.py
mathics/builtin/arithfns/basic.py
mathics/builtin/arithmetic.py
mathics/builtin/atomic/__init__.py
mathics/builtin/atomic/strings.py
mathics/builtin/atomic/symbols.py
mathics/builtin/base.py
mathics/builtin/box/graphics.py
mathics/builtin/box/inout.py
mathics/builtin/colors/color_directives.py
mathics/builtin/colors/color_operations.py
mathics/builtin/compilation.py
mathics/builtin/datentime.py

Possibly one or to more PRs like this to go.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/355"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Expression(SymbolList -> ListExpression or to_mathics_list

---

mathics/builtin/compilation.py
mathics/builtin/inout.py
mathics/builtin/manipulate.py
mathics/builtin/matrices/partmatrix.py
mathics/builtin/numbers/numbertheory.py
mathics/builtin/quantities.py
mathics/builtin/scipy_utils/optimizers.py
mathics/builtin/specialfns/gamma.py
mathics/builtin/string/charcodes.py
mathics/builtin/string/patterns.py
mathics/core/atoms.py
mathics/core/evaluation.py

More of the same.
There are some unconverted Expressions and ListExpressions remaining. These will require special attention I don't have time for right now. So that will be another PR. 
Until then I want to get the easier changes out of the way. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/358"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

List expression 3

---

mathics/builtin/base.py

We need to change leaves to elements in Pattern, but that will be some
other round in the future.
This inches forward though.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/364"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

leaves->elements at the Pattern boundary

---

mathics/builtin/base.py
mathics/builtin/drawing/image.py
test/builtin/numbers/test_nintegrate.py

and one more...
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/378"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

removing unnecesary cache in check_requires_list

---

mathics/builtin/drawing/image.py
mathics/doc/common_doc.py

Aft this check_requires_list-revision can be rebased and redone so it contains just the essentials for customization of Builtins based on Python packages available.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/382"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

remove np.bool warning and fix a typo

---

mathics/builtin/atomic/strings.py
mathics/builtin/patterns.py
mathics/builtin/recurrence.py
mathics/builtin/sparse.py
mathics/builtin/string/characters.py
mathics/builtin/string/charcodes.py
mathics/builtin/string/operations.py
mathics/builtin/string/patterns.py

Here we go with more modules...
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/384"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

More expression conversions 5

---

.github/workflows/windows.yml
CHANGES.rst
mathics/builtin/__init__.py
mathics/builtin/base.py
mathics/doc/common_doc.py
test/builtin/numbers/test_nintegrate.py

Seen also #376
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/383"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

more control over tests and doctest

---

mathics/builtin/atomic/symbols.py
mathics/builtin/colors/color_operations.py
mathics/builtin/drawing/plot.py
mathics/builtin/files_io/filesystem.py
mathics/builtin/optimization.py
mathics/builtin/procedural.py
mathics/core/evaluation.py
mathics/core/read.py

more canonicalization, more removing implicit conversions.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/386"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

more expression conversions

---

mathics/algorithm/optimizers.py
mathics/builtin/atomic/symbols.py
mathics/builtin/intfns/combinatorial.py
mathics/builtin/list/eol.py
mathics/builtin/list/rearrange.py
mathics/builtin/moments/basic.py
mathics/builtin/moments/special.py
mathics/builtin/numbers/algebra.py
mathics/builtin/numbers/calculus.py
mathics/builtin/numbers/integer.py
mathics/builtin/numbers/linalg.py
mathics/core/convert.py

the one before the last one...
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/389"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

More expression conversions 8

---

mathics/algorithm/parts.py
mathics/core/convert/expression.py

Inadvertently I committed the  first part of this in master. So look at the last few commits before this in master and if there are concerns or adjustments you can make them here. 
This is kind of the direction I'm going in. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/397"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

First use of make_expression.

---

CHANGES.rst
mathics/builtin/comparison.py
test/builtin/test_comparison.py
test/test_compare.py

Before:
```
In[1]:= 1 =!= 2 =!= 3 =!= 4
Out[1]:= 1 =!= 2 =!= 3 =!= 4
```
After:
```
In[1]:= 1 =!= 2 =!= 3 =!= 4
Out[1]= True
```

Update UnsameQ to accept any number of arguments

---

CHANGES.rst
mathics/builtin/arithmetic.py
mathics/builtin/intfns/divlike.py
mathics/builtin/intfns/misc.py
mathics/builtin/specialfns/gamma.py
mathics/core/expression.py

* CompositeQ
* Divisor
* ModularInverse
Also:
* move BernoulliB to a more suitable place in the code
* some attribute A_'s added
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/427"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

A few more Integer Functions

---

mathics/algorithm/parts.py
mathics/builtin/atomic/strings.py
mathics/builtin/attributes.py
mathics/builtin/binary/io.py
mathics/builtin/box/graphics.py
mathics/builtin/compilation.py
mathics/builtin/compile/ir.py
mathics/builtin/drawing/graphics3d.py
mathics/builtin/files_io/files.py
mathics/builtin/inout.py
mathics/builtin/list/eol.py
mathics/builtin/list/rearrange.py
mathics/builtin/numbers/algebra.py
mathics/builtin/numbers/diffeqns.py
mathics/builtin/options.py
mathics/builtin/string/charcodes.py
mathics/builtin/structure.py
mathics/builtin/tensors.py
mathics/core/convert/function.py
mathics/core/read.py
test/test_custom_boxconstruct.py

This doesn't get everything, but it narrows the use of get_elements().
Another PR will be needed to finish. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/429"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Reduce get elements

---

mathics/core/convert/function.py

Fixes #444
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/445"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Tolerate missing llvm

---

mathics/core/definitions.py
mathics/core/evaluators.py
mathics/doc/common_doc.py
mathics/docpipeline.py
test/builtin/numbers/test_nintegrate.py

Reverts Mathics3/mathics-core#453
This currently messes up current testing!

Revert "Add pymathics to docs"

---

mathics/builtin/atomic/strings.py
test/builtin/atomic/test_strings.py

Expand a little and simplify some.
Note that this would make an idea pymathics package
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/459"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Remove crash when name not found.

---

mathics/builtin/base.py
mathics/builtin/compilation.py
mathics/builtin/drawing/image.py
mathics/builtin/patterns.py
mathics/core/atoms.py
mathics/core/element.py
mathics/core/expression.py
mathics/core/pattern.py
mathics/core/rules.py
mathics/core/symbols.py

This is a first attempt to reimplement the sort keys as tuples.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/451"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

using tuple as sort key

---

mathics/core/systemsymbols.py

Small grammar typos and elaborations caught after the previous merge.

Doc correction.

---

mathics/builtin/intfns/combinatorial.py
mathics/builtin/intfns/divlike.py
mathics/builtin/intfns/misc.py
mathics/builtin/numbers/numbertheory.py

This PR fixes #456.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/464"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix attributes in new builtins

---

mathics/builtin/inout.py
mathics/builtin/numbers/numbertheory.py

While @mmatera does the hard stuff, I thought I would go back and do some easy stuff noticed in looking over those files.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/469"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Lint some recently changed files

---

mathics/doc/tex/mathics.tex

This PR put the mathics documentation pdf in a single column.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/475"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

two columns->one column

---

mathics/core/expression.py

This PR removes the last trailing references to `leaves` in `mathics.core.expression`. Also, the list of attributes in `Expression` is fixed.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/486"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Expression list of attributes

---

mathics/algorithm/introselect.py
mathics/builtin/drawing/__init__.py
mathics/builtin/statistics/dependency.py
mathics/builtin/statistics/orderstats.py

... And fill out "Graphics, Drawing, and Images links
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/489"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Go over Dependency and Dispursion Statistics urls

---

mathics/core/expression.py

_no_symbol() -> _does_not_contain_symbol(), add type annotations and simplify docstring
Remove Symbol definition redundancy and make explicit context for those remaining Symbol definitions
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/501"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

two small changes to Expression

---

mathics/builtin/base.py

and rename some variables for clarity and to avoid the name collision.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/524"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

removing duplicated loading loop for options in Builtin.contribute

---

mathics/builtin/atomic/numbers.py
mathics/builtin/list/rearrange.py
mathics/builtin/lists.py
mathics/builtin/numbers/algebra.py
mathics/builtin/numbers/integer.py
mathics/builtin/structure.py

This PR is the part of #522 that removes the duplicated symbols. We need to merge this in order to make that #522 now passes the tests.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/525"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

removing duplicated 1

---

mathics/builtin/box/layout.py
mathics/builtin/colors/color_directives.py
mathics/builtin/layout.py
mathics/builtin/makeboxes.py
mathics/builtin/quantities.py

This PR just sorts the classes in a lexicographical way in some modules.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/581"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

sorting classes in modules

---

CHANGES.rst
mathics/builtin/forms.py
mathics/core/definitions.py
mathics/core/formatter.py
mathics/core/symbols.py

WIP - first cut of use BaseForms ...
and marking forms for going into $PrintForms and $OutputForms
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/577"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add Form base class `FormBaseClass`

---

mathics/builtin/messages.py
mathics/builtin/options.py

and fix bug in handling a list of associations
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/594"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

SetOption error message detection..

---

CHANGES.rst
SYMBOLS_MANIFEST.txt
mathics/builtin/assignments/clear.py

This PR adds the `Remove` builtin
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/598"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

adding Remove

---

mathics/builtin/base.py
mathics/builtin/patterns.py
mathics/core/element.py
mathics/core/evaluation.py
mathics/core/rules.py

With these changes, over #616, https://github.com/jkuczm/MathematicaSyntaxAnnotations/blob/master/SyntaxAnnotations/SyntaxAnnotations.m finally loads without killing the session.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/618"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix get_sort_key second argument and BoxExpression.sameQ. 

---

mathics/builtin/__init__.py
mathics/compile/__init__.py
mathics/core/__init__.py
mathics/core/convert/__init__.py
mathics/core/parser/__init__.py
mathics/eval/__init__.py

Note: the decriptive text will also be duplicated in the Mathics Developer's Guide.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/646"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Document some top-level python modules

---

mathics/builtin/__init__.py

It appears in test/consistency-and-style/test_summary_text.py

Remove run-time summary-check code.

---

admin-tools/build_and_check_manifest.py
mathics/builtin/__init__.py
mathics/core/definitions.py
mathics/core/pymathics.py
mathics/doc/common_doc.py
mathics/format/mathml.py

These changes have been split off from #631. That other PR will have to be rebased after this and #651 go in.

Miscelleneous lint found in files of #631

---

mathics/builtin/mainloop.py

Some typos corrected. WMA links added. isort imports and go over some Pycharm lint messages.

Lint mainloop

---

mathics/builtin/specialfns/bessel.py
mathics/builtin/specialfns/elliptic.py
mathics/builtin/specialfns/expintegral.py
mathics/builtin/specialfns/gamma.py
mathics/builtin/specialfns/zeta.py
mathics/builtin/statistics/dependency.py
mathics/builtin/statistics/location.py
mathics/builtin/statistics/orderstats.py
mathics/builtin/string/characters.py
mathics/builtin/string/charcodes.py
mathics/builtin/string/operations.py
mathics/builtin/string/patterns.py
mathics/builtin/string/regexp.py

Here we go with the first bunch from #668. There are 14 in total, covering three submodules.

url in docstrings for modules   string - statistic - specialfns

---

mathics/builtin/binary/bytearray.py
mathics/builtin/colors/color_operations.py
mathics/builtin/drawing/image.py
mathics/builtin/drawing/image_internals.py
mathics/builtin/list/eol.py

Further passes to get to standards
* dd indentation
* isort modules
* Ensure <url> lines are under 80 characters
* `eol`: order Builtin
* some numpy.bool -> bool
* apply -> eval

Further passes to get to standards

---

mathics/builtin/binary/bytearray.py
mathics/builtin/colors/color_operations.py
mathics/builtin/drawing/image.py
mathics/builtin/drawing/image_internals.py
mathics/builtin/list/eol.py

This contains the docstring fixes in modules used in https://github.com/Mathics3/mathics-core/tree/ByteArray-box (see comment https://github.com/Mathics3/mathics-core/pull/669#issuecomment-1362618569)

doc for required modules

---

mathics/core/atoms.py

Starts to split off more of #665
We need `__new__` anyway to compute hash values.
In some cases we can canonicalize object by value, e.g. for Rational by reducing the value.
Document better what is going on here.

Remove @lru_cache in favor of homegrown cache

---

mathics/builtin/arithmetic.py

add  descriptive (wiki) name for Arg

Further doc tweaks

---

CHANGES.rst
mathics/__init__.py
mathics/doc/common_doc.py
mathics/main.py
mathics/system_info.py
setup.py

* Allow Sympy 1.12
* Provide list of optional software for each list its version.
* tweak Windows and PyPy detection
* provide versions on optional packages; this will be used in front-ends
* Update CHANGES.rst for this and some recent changes.

Version tweaking

---

mathics/builtin/arithfns/basic.py
mathics/builtin/arithmetic.py
mathics/builtin/base.py
mathics/builtin/numbers/numbertheory.py
mathics/builtin/specialfns/erf.py

Improper apply name reduction

---

mathics/builtin/image/base.py
mathics/eval/image.py

This fix the issue in importing PIL.Image in pyston

fix PIL.Image import

---

mathics/builtin/files_io/importexport.py

This fix an issue in building the pdf documentation, and improves the documentation of the corresponding symbols.

Improving tests and examples for FormatMapping

---

mathics/builtin/specialfns/zeta.py
mathics/doc/latex_doc.py

Latex doc tweaks

---

mathics/__init__.py
mathics/builtin/assignments/clear.py
mathics/builtin/atomic/atomic.py
mathics/builtin/atomic/numbers.py
mathics/builtin/base.py
mathics/builtin/files_io/importexport.py
mathics/doc/latex/Makefile

Update Copyright.
Some apply -> eval adjustments
"make pdf" is a shorthand for "make mathics.pdf"

Ring in 2023!

---

mathics/core/evaluation.py

This came up when I was considering a larger refactor of testing and doc generation

Small changes to Result class.

---

mathics/builtin/colors/color_operations.py

Had thought I had included this previously, but with various merges and rebases it got lost.

Improve ColorNegate doc

---

setup.py

Recordclass now seems to require this.

Require cython

---

mathics/builtin/specialfns/elliptic.py
mathics/builtin/specialfns/gamma.py

Basically what I have time for in the next batch
apply->eval add some links to Wikipedia and SymPy

Make a pass over these special functions

---

mathics/builtin/arithmetic.py
mathics/builtin/base.py
mathics/builtin/list/constructing.py
mathics/builtin/lists.py
mathics/builtin/procedural.py
mathics/eval/numbers.py
mathics/eval/scoping.py

* Move mathics.builtin.list._IterationFunction to mathics.base.IterationFunction
* Move eval-like routines out of mathics.builtin.arithmetic into mathics.eval.numbers
* Move scoping routine out of builtin.base into mathics.eval.scoping

builtin.list reduction mathics.eval expansion..

---

mathics/builtin/specialfns/bessel.py
mathics/builtin/statistics/dependency.py
mathics/builtin/statistics/location.py
mathics/builtin/statistics/orderstats.py
mathics/builtin/string/characters.py

apply -> eval, split long lines, evaluation annotation type

More of the same --

---

mathics/data/ExampleData/copyright.csv

Update this to reference the original source of this document.
Fixes: #730

ExampleData: update copyright byline for Namespaces.xml

---

mathics/builtin/forms/output.py
mathics/builtin/matrices/partmatrix.py
mathics/builtin/messages.py
mathics/builtin/numeric.py
mathics/builtin/optimization.py
mathics/builtin/recurrence.py
mathics/core/rules.py

Reuse StringLParen and StringRparen
type Annotation on evaluation

apply->eval and minor tweaks

---

CHANGES.rst
mathics/builtin/numbers/randomnumbers.py

Add Random[]. We also assume some sort of NumPy

---

CHANGES.rst
SYMBOLS_MANIFEST.txt
mathics/builtin/drawing/plot.py

I was looking over https://www.wolfram.com/language/elementary-introduction/2nd-ed/04-displaying-lists.html and saw `NumberLinePlot` and thought this would be easy to add - at least it its most rudimentary form. 
If others want to add more complicated forms, have at it.

Add rudimentary NumberLinePlot

---

mathics/builtin/lists.py
mathics/builtin/messages.py
mathics/builtin/system.py

Just moving builtins in https://reference.wolfram.com/language/guide/Messages.html to mathics.builtin.messages and sorting the classes

Moving builtins to message

---

mathics/builtin/__init__.py
mathics/core/pymathics.py
mathics/doc/common_doc.py
test/builtin/drawing/test_image.py
test/consistency-and-style/test_duplicate_builtins.py
test/consistency-and-style/test_summary_text.py

@mmatera These are changes I needed to make to get "pymathics.graph" and "pymathics.hello" to work.
Please review for reasonableness. 
To check these use the mathics-6.0.0 branches of each of those repositories.

Changes needed to get Pymathics working again

---

CHANGES.rst
mathics/algorithm/integrators.py
mathics/builtin/atomic/numbers.py
mathics/builtin/colors/color_directives.py
mathics/builtin/colors/color_internals.py
mathics/builtin/distance/clusters.py
mathics/builtin/forms/output.py
mathics/builtin/numbers/calculus.py
mathics/builtin/numbers/constants.py
mathics/builtin/numeric.py
mathics/builtin/specialfns/bessel.py
mathics/core/atoms.py
mathics/core/convert/mpmath.py
mathics/core/convert/sympy.py
mathics/core/number.py
mathics/core/parser/convert.py
test/builtin/colors/test_colors.py

This is another round of changes in tiding up the arithmetic/precision code.

renaming constants according to Python convension.

---

mathics/builtin/arithmetic.py
mathics/builtin/numbers/constants.py
mathics/builtin/specialfns/gamma.py
mathics/core/atoms.py
mathics/core/convert/mpmath.py
mathics/eval/nevaluator.py
test/builtin/atomic/test_numbers.py

This PR fixes another issue with precision. In particular, this issue was the reason of the hangings in doctest in #778.

fix mpmath precision handling

---

mathics/builtin/atomic/numbers.py
mathics/builtin/numbers/constants.py
mathics/core/convert/expression.py
mathics/core/expression.py
mathics/doc/common_doc.py

Pull out get_section_tests as its own method.

spelling corrections, some type corrections & doc.

---

.github/workflows/osx.yml
.github/workflows/ubuntu-cython.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
CHANGES.rst
PAST.rst
mathics/builtin/atomic/numbers.py
mathics/builtin/options.py
mathics/builtin/specialfns/elliptic.py
mathics/version.py
setup.py

Last push for 6.0.0
* Adjust version
* Last go over for spelling
* Require Mathics-scanner1.3.0
* Update changes

Release 6.0.0

---

mathics/builtin/base.py
mathics/builtin/patterns.py
mathics/core/pattern.py
mathics/core/rules.py
test/core/test_rules.py

This is the part of #804 involving only documentation fixes, adding annotations and pytests.

More docs and annotations about Pattern and Rules

---

mathics/core/parser/ast.py
mathics/core/parser/parser.py

I will start aadding RowBox, SuperscriptBox, SubscriptBox, UnderscriptBox, FractionBox, RadicalBox, FormBox parsing shortcuts. But before that there is this stuff to modernize the code according to current practice, type annotations, adding some literals, etc.

Parsing annotations and modernization

---

mathics/packages/Utilities/CleanSlate.m

... and I wonder what other packages like this we can just add.

Add CleanSlate package

---

mathics/core/convert/mpmath.py
test/core/convert/mpmath.py

This PR improves the annotations and the implementation of `from_mpmath`. Also, some pytests are included.

improve from_mpmath. adding pytests

---

mathics/builtin/specialfns/gamma.py
mathics/core/number.py
mathics/eval/arithmetic.py

Also, a number of other small style changes, and grammar corrections were done as well.

Cache via lru_cache mpmath calls

---

mathics/eval/arithmetic.py

Note weakness in type check. Also, remove done TODOs.

Tidy a little more

---

mathics/session.py

This PR is just a temporal patch. At some point we need to really face the modularity issue in the design of `mathics.format`.

temporal patch for #844

---

mathics/builtin/string/regexp.py
test/core/convert/test_to_regex.py

More tweaks for 3.11 support preparation

---

.github/workflows/consistency-checks.yml
.github/workflows/isort-and-black-checks.yml
.github/workflows/osx.yml
.github/workflows/ubuntu-cython.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

adding 3.11 to the CI

---

mathics/builtin/files_io/filesystem.py
mathics/core/number.py

* DRY Handle invalid compiling filenames in FileNames
* fewer polymorphic variables in this code
* A number of style things
Not done, but it would be nice to have more pytests for FileSystem.

Go over `mathics.builtin.files_io.filesystem`

---

mathics/builtin/__init__.py
mathics/builtin/directories/__init__.py
mathics/builtin/directories/directory_names.py
mathics/builtin/directories/directory_operations.py
mathics/builtin/file_operations/__init__.py
mathics/builtin/file_operations/file_properties.py
mathics/builtin/file_operations/file_utilities.py
mathics/builtin/files_io/filesystem.py
mathics/core/systemsymbols.py
mathics/doc/common_doc.py
mathics/eval/directories.py

Split out section previously under: Input/Output, Files, and Filesystem
There are a couple more sections: "User File Directories " and "System File Directories"  that should be split out as well. 
However this PR is already a bit large.

Start to out mathics.builtin.files.io.filesystem

---

mathics/builtin/drawing/graphics3d.py
mathics/builtin/drawing/graphics_internals.py
mathics/builtin/procedural.py
mathics/main.py
mathics/timing.py

small styling stuff of misc files looked a in looking for preformance bottlnecks

Add --cprofile option to main and

---

mathics/builtin/lowlevelprofile.py
mathics/docpipeline.py

Here is a proposal for a Builtin symbol that produces a Low-level profile of the evaluation.

adding PythonCProfileEvaluation Builtin

---

.github/workflows/consistency-checks.yml
.github/workflows/isort-and-black-checks.yml
.github/workflows/osx.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

Nothings special or important about v4 over v2 or v3; just keeping current.

Try actions-setup v4

---

mathics/builtin/arithmetic.py
mathics/eval/arithmetic.py

This PR fixes the `RealSign` docstring and removes a trailing unreachable piece of code in the `eval_Sign` function.

trailing changes

---

mathics/builtin/assignments/assignment.py
mathics/builtin/assignments/clear.py
mathics/builtin/image/base.py
mathics/builtin/image/basic.py
mathics/builtin/image/composition.py
mathics/builtin/image/geometric.py
mathics/builtin/image/misc.py
mathics/builtin/image/pixel.py
mathics/builtin/image/properties.py
test/builtin/image/test_image.py
test/builtin/test_assignment.py

Moving private doctests to pytest for assignment and image

---

mathics/builtin/testing_expressions/numerical_properties.py

Correct EvenQ summary test.

---

CHANGES.rst
mathics/builtin/quantities.py
mathics/eval/makeboxes.py
mathics/eval/quantities.py
test/builtin/test_quantities.py

This part required some changes in `mathics.builtin.quantity`, because the original one was not compatible with MathicsSession evaluation.

moving Quantity private doctests to pytests.

---

mathics/core/convert/sympy.py

adding doctrings, using formatted strings, and simplifying conditionals.

fix some pylinter warnings

---

mathics/builtin/physchemdata.py
mathics/builtin/statistics/orderstats.py
mathics/builtin/tensors.py
mathics/builtin/vectors/vector_space_operations.py
test/builtin/test_physchemdata.py
test/builtin/test_statistics.py
test/builtin/test_tensor.py
test/builtin/vectors/test_vector_space_operations.py

moving private doctests to pytests for physchemdata, tensor, statistics and vector

---

mathics/builtin/exp_structure/general.py
mathics/builtin/exp_structure/size_and_sig.py
mathics/builtin/functional/application.py
mathics/builtin/functional/apply_fns_to_lists.py
mathics/builtin/functional/functional_iteration.py
test/builtin/test_exp_structure.py
test/builtin/test_functional.py

move private doctests to pytests for exp_structure and fuctional

---

mathics/builtin/testing_expressions/equality_inequality.py
mathics/builtin/testing_expressions/list_oriented.py
mathics/builtin/testing_expressions/logic.py
mathics/builtin/testing_expressions/numerical_properties.py
test/builtin/test_testing_expressions.py

and the last one for this Sunday...

moving private doctests to pytest for testing_expressions

---

mathics/core/assignment.py

This PR fixes a logical bug found in your code.
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [assignment.py](https://github.com/Mathics3/mathics-core/blob/master/mathics/core/assignment.py#L164), method: `repl_pattern_by_symbol`, a logical equality check operation was performed with the same operand on both sides. The comparison operation always returns either true or false. Such logical short circuits in code lead to unintended behavior. iCR suggested that the logical operation should be reviewed for correctness.
After reviewing the logic in the method, I've updated the comparsion for `element` before and after `repl_pattern_by_symbol()` method invocation. Also, I used logical operators such as `==` or `!=` to compare element objects. …

Fixed Inappropriate Logical Expression

---

mathics/builtin/forms/variables.py

Correct Format in $PrintForm example

---

mathics/packages/DiscreteMath/CombinatoricaV0.9.m

* Slight grammar change
* Make it more clear that we've modified this.

Small tweaks

---

.github/workflows/consistency-checks.yml
.github/workflows/isort-and-black-checks.yml
.github/workflows/osx.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
mathics/core/evaluation.py
mathics/doc/documentation/1-Manual.mdoc
mathics/doc/utils.py
mathics/docpipeline.py

There are some small changes which fall outside of docpipeline and common_doc. It would be good to address these outside of the massive PR that is building up.

Some small changes noticed in revising doctest

---

.github/workflows/isort-and-black-checks.yml
.pre-commit-config.yaml
mathics/builtin/assignments/assignment.py
mathics/builtin/atomic/numbers.py
mathics/builtin/atomic/strings.py
mathics/builtin/box/graphics.py
mathics/builtin/drawing/plot.py
mathics/builtin/files_io/files.py
mathics/builtin/files_io/importexport.py
mathics/builtin/graphics.py
mathics/builtin/image/base.py
mathics/builtin/intfns/combinatorial.py
mathics/builtin/list/eol.py
mathics/builtin/numbers/algebra.py
mathics/builtin/numbers/calculus.py
mathics/builtin/optimization.py
mathics/builtin/pympler/asizeof.py
mathics/builtin/recurrence.py
mathics/builtin/testing_expressions/equality_inequality.py
mathics/core/expression.py
mathics/core/pattern.py
mathics/doc/latex/doc2latex.py
mathics/eval/image.py
mathics/eval/quantities.py
mathics/format/asy.py
test/builtin/test_compile.py
test/format/test_svg.py
test/helper.py
test/package/test_combinatorica.py
test/test_combinatorial.py

Python 3.11 has runs into trouble installing poetry for black.

Bump versions in pre-commit hook -

---

mathics/builtin/files_io/files.py
mathics/core/definitions.py
mathics/core/read.py
mathics/main.py

Currently $InputFileName returns always an empty string.
The commit fixes this wrong behaviour, I don't know if I did it in the optimal way.

Fix $InputFileName

---

mathics/builtin/image/misc.py

Just fix the doctest that produces the error in #999 (probably because that PR fixes something that makes the test to run)

Fix textrecognize doctest

---

mathics/builtin/assignments/assignment.py

Just a tiny change in the doctest

Fix doctest for TagSet

---

mathics/builtin/assignments/assignment.py

Adjust UpSet doctest to be clearer

---

test/builtin/test_directories.py
test/doc/test_common.py

This is the part of pytests in #999.

fix pytests

---

.github/workflows/ubuntu-cython.yml
.github/workflows/ubuntu.yml

This is what happens with the original SameQ

Replacing 3.11 to 3.12 in Cython workflow 

---

CHANGES.rst
mathics/builtin/procedural.py

Just basic implementation. Right now, we don't handle options.

Start CheckAbort[] builtin function

---

mathics/builtin/testing_expressions/numerical_properties.py
pyproject.toml

Allow SymPy up to but not including SymPy 1.14.

Try SymPy 1.13+

---

.github/workflows/macos.yml
CHANGES.rst
mathics/builtin/box/compilation.py
mathics/core/pattern.py

Note API incompatibilty introduced in Pattern changes Adjust pattern comment
Remove Lint warning on compilation box

A few small changes -

---

CHANGES.rst
FUTURE.rst

See also https://github.com/Mathics3/mathics-core/discussions/961

Go over FUTURE and CHANGES

---

mathics/core/__init__.py
mathics/main.py
test/test_main.py
test/test_main_preeval.py

This allows us to modify definitions at the top-level to trace or debug.

Add PRE_EVALUATION_HOOK to facilitate debugging.

---

mathics/eval/nevaluator.py
test/core/test_is_literal.py

Remove unnecessary evaluations for literal List evaluations.

Speed up list processing

---

mathics/builtin/numbers/numbertheory.py
mathics/builtin/statistics/orderstats.py

I pulled out just the number theory builtins (and ReverseSort) from #1133

Add missing builtins: number theory

---

.github/workflows/consistency-checks.yml
SYMBOLS_MANIFEST.txt
admin-tools/build_and_check_manifest.py
mathics/builtin/atomic/strings.py
mathics/builtin/files_io/filesystem.py
mathics/builtin/numbers/constants.py

This PR just fixes and reinstall the SYMBOL_MANIFEST consistency check, to avoid erase/ duplicate symbols.

fixing check manifest

---

CHANGES.rst
mathics/builtin/numbers/calculus.py

Doc text in Django before: 
after:

Add RootSum to CHANGES & doc formatting

---

mathics/builtin/atomic/numbers.py
mathics/builtin/list/constructing.py
mathics/builtin/list/rearrange.py
mathics/builtin/numbers/algebra.py
mathics/builtin/numbers/calculus.py
mathics/builtin/numbers/numbertheory.py
mathics/core/element.py
mathics/core/expression.py

This just fixes a few crashes I was seeing running Mathics through OEIS programs, with corresponding doctests (and a few more type error fixes)

Miscellaneous fixes

---

mathics/docpipeline.py

Just to help me see when I have run the test shown in a window.

show  date and time at the end of a doctest run

---

mathics/eval/files_io/files.py
test/builtin/files_io/test_files.py

See the `ReadList[]` example in https://github.com/Mathics3/Mathics3-Rubi/pull/2

`ReadList[]`  handling `Null` and `Hold[]` expressions

---

mathics/builtin/atomic/strings.py
mathics/builtin/files_io/importexport.py
mathics/core/parser/convert.py
mathics/core/parser/parser.py
test/core/parser/test_parser.py

Move unescaping string from "convert" to parsing (mostly - filenames might be done in a later step).
A number of small miscellaneous tweaks and mistakes found in looking over the code.

Misc changes in advance of Box expression parsing

---

mathics/builtin/files_io/files.py
mathics/builtin/intfns/recurrence.py
mathics/builtin/patterns/rules.py
mathics/core/assignment.py
mathics/core/attributes.py
mathics/core/convert/python.py
mathics/core/element.py
mathics/core/expression.py
mathics/core/load_builtin.py
mathics/core/parser/parser.py
mathics/core/pattern.py
mathics/core/streams.py
mathics/core/structure.py
mathics/core/subexpression.py
mathics/core/symbols.py
mathics/doc/documentation/1-Manual.mdoc
mathics/doc/images.sh
mathics/doc/latex/Makefile
mathics/doc/latex/README.rst
mathics/doc/latex/doc2latex.py

fix some typos

---

mathics/builtin/numbers/calculus.py
mathics/builtin/numbers/randomnumbers.py
mathics/core/convert/sympy.py
mathics/core/definitions.py
mathics/core/subexpression.py
mathics/eval/numbers/calculus/integrators.py
mathics/eval/numbers/calculus/series.py

as it is better to avoid creating the inner list
`ruff` code C419

simplify some all(...) and any(...)

---

mathics/builtin/numbers/trig.py
test/builtin/numbers/test_trig.py

Add rule for ArcTan[ComplexInfinity]

---

mathics/builtin/makeboxes.py
mathics/core/builtin.py
mathics/core/parser/README.md
mathics/core/parser/operators.py
mathics/core/parser/parser.py
mathics/eval/makeboxes.py
test/builtin/arithmetic/__init__.py
test/builtin/list/__init__.py
test/core/parser/__init__.py

Originally I wanted to make progress on Box operator parsing. However as happens too often, before I can make forward progress it is useful to clean things up and document the current state. 
This is not getting a bit large, so probably we should do the clean up work separate from the box operators to follow.

Parsing refactor

---

mathics/core/parser/parser.py
mathics/data/.gitignore
test/core/parser/test_box_parser.py
test/core/parser/test_parser.py

A first cut at detecting nested box operators.

Add code to recognize nested box operators

---

mathics/core/evaluation.py
mathics/core/load_builtin.py
mathics/eval/inference.py
mathics/session.py

* More docstrings.
* More on reducing pylint warnings. 
* Simplifying access to values and rules using `Definitions.get_*` methods.

More on tidy up the code 

---

mathics/builtin/testing_expressions/equality_inequality.py

Just adding the requested rule.

Between rule for several intervals

---

mathics/docpipeline.py

fix docpipeline report

---

mathics/builtin/arithfns/basic.py
mathics/builtin/arithmetic.py
mathics/builtin/files_io/importexport.py
mathics/builtin/functional/apply_fns_to_lists.py
mathics/builtin/testing_expressions/equality_inequality.py
mathics/builtin/trace.py
mathics/core/builtin.py
mathics/doc/documentation/1-Manual.mdoc
mathics/doc/latex/Makefile
mathics/docpipeline.py
test/builtin/arithmetic/test_basic.py
test/builtin/test_evaluation.py

* New tests in `test.builtin.arithfns.test_basic`
* fix `mathics.builtin.arithfns.basic` formatting rules for Plus and Times.

Lint two pytests

---

mathics/builtin/arithmetic.py
mathics/builtin/file_operations/path_operations.py
mathics/builtin/system.py

Doctest corrections for Arg, FilenameDrop and SetEnvironment. 
SetEnvironment return value corrected.

Docfixes part2

---

CHANGES.rst
README.rst
mathics/builtin/intfns/recurrence.py
mathics/builtin/numbers/numbertheory.py
mathics/builtin/specialfns/expintegral.py

Fold in some public comments on release changes. Another pass at new builtin function docstrings.

Start noting broad changes

---

CHANGES.rst
mathics/builtin/atomic/numbers.py
mathics/builtin/intfns/combinatorial.py
mathics/builtin/intfns/recurrence.py

More edits in `CHANGES.rst`
Go over functions up to PolygonalNumber

Note more of the many changes

---

.github/workflows/consistency-checks.yml
.github/workflows/mypy.yml
.github/workflows/pyodide.yml
.github/workflows/ubuntu-cython.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
.pre-commit-config.yaml
CHANGES.rst
ChangeLog-spell-corrected.diff
Makefile
mathics/version.py
pyproject.toml

Perform mostly administrative stuff that is needed for release. Change version number, use PyPI mathics-scanner, update CHANGES.rst, etc.

Release 8.0.0

---

mathics/builtin/atomic/atomic.py
mathics/builtin/atomic/numbers.py
mathics/builtin/atomic/strings.py
mathics/builtin/atomic/symbols.py
mathics/builtin/box/layout.py
mathics/builtin/colors/color_directives.py
mathics/builtin/colors/color_operations.py
mathics/builtin/directories/directory_names.py
mathics/builtin/directories/directory_operations.py
mathics/builtin/distance/clusters.py
mathics/builtin/distance/numeric.py
mathics/builtin/distance/stringdata.py
mathics/builtin/drawing/graphics3d.py
mathics/builtin/drawing/plot.py
mathics/builtin/drawing/splines.py
mathics/builtin/graphics.py
mathics/builtin/manipulate.py

Dd fixes 03

---

mathics/builtin/numbers/calculus.py
mathics/builtin/specialfns/elliptic.py
mathics/builtin/specialfns/orthogonal.py
mathics/builtin/vectors/constructing.py
mathics/doc/doc_entries.py

This PR modifies the code that generates the text shown in `Information`.
* Remove escape characters
* symbols with subindices are resembled as valid variable names.

Adjust the plain-text form of documentation

---

test/doc/test_common.py
test/doc/test_doctests.py

Remove duplicated doctest

---

pyproject.toml

Allow using numpy 2  (up to 2.3).

Try using numpy < 2.3

---

mathics/builtin/intfns/combinatorial.py

Go over docstring tagging for combinatorial functions and add mostly wiki links to related material.

doc tagging and links for combinatorial builtins

---

mathics/builtin/drawing/uniform_polyhedra.py
mathics/builtin/quantum_mechanics/angular.py

Here are fixes for a couple of tiny typos.

Add asy dodecahedron mm

---

mathics/builtin/arithmetic.py
mathics/builtin/drawing/plot.py
mathics/builtin/functional/application.py
mathics/builtin/image/test.py
mathics/builtin/intfns/combinatorial.py
mathics/builtin/intfns/misc.py
mathics/builtin/intfns/recurrence.py
mathics/builtin/list/associations.py
mathics/builtin/mainloop.py
mathics/builtin/numbers/constants.py
mathics/builtin/numbers/diffeqns.py
mathics/builtin/numbers/numbertheory.py
mathics/builtin/options.py
mathics/builtin/patterns/composite.py
mathics/builtin/physchemdata.py
mathics/builtin/quantum_mechanics/angular.py
mathics/builtin/scoping.py
mathics/builtin/specialfns/expintegral.py
mathics/builtin/vectors/vector_space_operations.py
mathics/doc/doc_entries.py

Another round. More fixes to typos in the documentation. Now `<console>...</console>` handles multiline entries.

small fix to the CONSOLE_RE. Several fixes for typos in documentation

---

mathics/builtin/options.py
mathics/builtin/patterns/composite.py

Option-related things noticed in trying (unsuccessfully) to get MUnit working...
* Adjust `OptionValue` error messages to align better with WMA.
* Go over `Options`, `OptionValue`, and `OptionsPattern` docs.
* Lint code a little

Option management tweaks

---

mathics/builtin/specialfns/gamma.py

Fixes #1388 @axkr does this do the trick?

Revise Pochhammer for negative n values.

---

CHANGES.rst
SYMBOLS_MANIFEST.txt
mathics/autoload/formats/CSV/Import.m
mathics/builtin/binary/io.py
mathics/eval/binary/io.py

Add `ReadList` and split off read evaluation routine into  `mathics.eval.io.eval_Read`

Add `BinaryReadList[]`

---

mathics/builtin/list/eol.py
mathics/builtin/testing_expressions/expression_tests.py
mathics/builtin/testing_expressions/logic.py

Down the line when documentation is redone, there could be more. For now, I am adding the one that I personally find useful in using the existing docs.

Add a couple of "See also" links.

---

.github/workflows/consistency-checks.yml
.github/workflows/macos.yml
.github/workflows/mypy.yml
.github/workflows/packages.yml
.github/workflows/pyodide.yml
.github/workflows/ubuntu-cython.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
CHANGES.rst
mathics/core/parser/parser.py
mathics/eval/files_io/files.py
test/core/parser/test_box_parser.py

For now, we support only  `\( ... \*` _BoxFunction_[...] `\)`

Start supporting Box input escape \*

---

mathics/eval/assignments/assignment.py
test/builtin/assignments/test_assignment.py

Improving tag collection in tag assignment

---

mathics/eval/symbolic_history/stack.py
mathics/eval/tracing.py
test/builtin/symbolic_history/test_stack.py

Fixing Trace[] crash

---

mathics/builtin/options.py
mathics/builtin/quantities.py
mathics/core/util.py
mathics/eval/quantities.py
test/builtin/test_quantities.py

Correct documentation for `QuantityQ[]`.
Add parameter number checking. 
Fixes #1474

Correct doc for QuantityQ, add param # checking

---

mathics/session.py

With this, it seems all the tests pass now

reset iteration_count in session

---

mathics/builtin/atomic/strings.py
mathics/builtin/codetables.py
mathics/builtin/numeric.py
mathics/builtin/procedural.py
mathics/builtin/quantities.py
mathics/core/builtin.py
mathics/core/expression.py
test/builtin/atomic/test_strings.py
test/builtin/test_procedural.py

Checks added to 'If', 'While', and 'Throw'. 
We start to handle 'argb' tag, "between x and y".

More parameter checks
