mathics/builtin/string/operations.py, test/test_strings.py
Add WL tests, revise doc
We should not be using #> except to test error messages. Instead, these should be moved to pytest where they run faster.
Revise documentation for StringSplit. Note that carriage returns are hard returns, not wrapped. They will appear in docs.
Describe more about why we are showing the examples shown.
Add summary text for more strings operations
=> More string split tests and doc

mathics/builtin/string/operations.py, mathics/builtin/string/patterns.py, test/test_strings.py
Continuation of [Mathics#1456](https://github.com/mathics/Mathics/pull/1456).
=> Fix `StringSplit`'s missing whitespaces

Makefile
@mmatera `make clean-cython && make`  is what should be used in between benchmark runs when you need to switch git SHA. 
This branch adds the `make clean-cython` part.
=> Add clean-cython target

mathics/builtin/assignment.py, test/test_assignment.py, test/test_help.py
Recenty we have been filling out `summary_text` for Built-in Functions.
This text currently appears in Django when it is listed in a group. See for example "Operations on Strings".
This PR expands that use so that this short text also appears when `?xxx` or `Information[xxx, LongForm->False]` is requested.
=> Use Builtin class summary_text in `?`

mathics/builtin/arithfns/basic.py, mathics/builtin/arithmetic.py, mathics/builtin/comparison.py, mathics/builtin/compilation.py, mathics/builtin/drawing/graphics3d.py, mathics/builtin/drawing/plot.py, mathics/builtin/graphics.py, mathics/builtin/lists.py, mathics/builtin/numeric.py, mathics/builtin/patterns.py
Continuation of [Mathics#1582](https://github.com/mathics/Mathics/pull/1582).
Replace `Expression("N", ...).evaluate(...)` and `Expression(SymbolN, ...).evaluate(...)` by `apply_N(...)` everywhere it's possible.
This approach is faster.
=> Use `apply_N` more intensively

.editorconfig, .github/workflows/osx.yml, .github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, CHANGES.rst, Makefile, requirements-cython.txt, setup.py
Set environment variable NO_CYTHON before running setup.py to avoid
running Cython even if it is installed.
=> Allow a developer to overide to running Cython

mathics/algorithm/parts.py, mathics/builtin/assignment.py, mathics/builtin/base.py, mathics/builtin/exceptions.py, mathics/builtin/list/eol.py, mathics/builtin/lists.py, mathics/builtin/numbers/algebra.py, mathics/builtin/patterns.py, mathics/builtin/sparse.py, mathics/builtin/string/operations.py, mathics/builtin/tensors.py, setup.py
* move all the "algorithmic" routines in `mathics.core.lists` to an independent module in `mathics.algorithm.parts`
* cithonize `mathics.algorithm.parts`
* fix all the warnings produced by flake8
* Move `Exception` classes from `mathics.builtin.base` to `mathics.builtin.exceptions` to avoid circular references.
=> Lists overhaul

mathics/builtin/drawing/plot.py
One of the slowest tests in `docpipeline` are the ones associated with Spherical Bessel functions. In particular, the ones that plot these functions. This was due to a wrong implementation of the numerification (is that the word?) of the functions to be plotted in
`mathics.builtin.drawing.Plot_`.
This PR
* Improves rules for SphericalBesselFunction(J/Y) to make the evaluation faster
* Fixes in the plot routine, that numerify expressions
=> Faster Plot

mathics/builtin/box/graphics3d.py, mathics/format/json.py
This replaces a temporary fix in the JSON function of the 3d Point
by a function-replacement in Point3DBox.
The temporary fix was converting the color from white to black. This was
done because the default color is white, and it should be black for the
points.
=> Allow white 3d points

mathics/builtin/lists.py, mathics/builtin/numbers/calculus.py, mathics/builtin/numbers/diffeqns.py, mathics/doc/documentation/1-Manual.mdoc
This PR changes the behavior of MakeBoxes[List[___], FullForm] to make it closer to WMA. 
```
In[1] := FullForm[List[1,2,3]]
Out[1]:= {1,2,3}
```
This also helps to debug some code like the one in ``Series``, which can produce several nested lists.
=> List fullform

mathics/builtin/__init__.py
This PR fixes some flakiness I found during the `Definitions` refactoring: `mathics.builtin.box.*` was not loaded during the startup.
=> load mathics.builtin.box

CHANGES.rst, mathics/core/definitions.py
This PR is a small part of #64 that helps to access the current context and the context without the need to look at the corresponding definition. These variables are intensively used each time that the context of a symbol needs to be resolved.
=> faster access to Context and ContextPath

CHANGES.rst, mathics/builtin/inout.py, mathics/core/definitions.py, mathics/core/evaluation.py, mathics/core/expression.py, mathics/core/symbols.py
TraceEvaluation fits more regularly into the other Trace routines and is more likely to be found when running say `Names["Trace*"]` or looking this up from Django.
=> ShowSteps -> TraceEvaluation

mathics/builtin/logic.py
This PR adds the `Locked` attribute to ```System`True``` and ```System`False```  according to the WL standard.
=> fixing attributes for True and False

mathics/builtin/numbers/calculus.py, setup.py
Sympy 1.9 is out and it seems to work without problems. Allow (but don't require) it.
=> Allow using Sympy 1.9

CHANGES.rst, mathics/core/atoms.py
The evaluation is still slow, but this avoids the overflow. There are two things that could be improved:
* to check the size of the number before the conversion, to avoid using an exception.
* the default value of `d` could be taken from `mathics.core.number`  instead of hardcoding it to 15.
=> fix N (Issue #103)

mathics/builtin/base.py, mathics/builtin/list/eol.py, mathics/builtin/lists.py, mathics/builtin/strings.py, mathics/builtin/structure.py, mathics/core/subexpression.py
Don't use imports as a way to reexport a name that isn't used in the module.
Some other small changes were made as well.
=> Mostly untangle imports

CHANGES.rst, mathics/builtin/numbers/constants.py, mathics/builtin/numeric.py, mathics/core/atoms.py, mathics/core/evaluation.py, mathics/core/number.py, mathics/core/symbols.py
In this PR a method to propagate the choice of the method used to compute constants is implemented. Also, this should clarify the interface for defining built-in `NValues` rules:  Now, all the builtin rules for ``N``  has the form ``N[expr_,prec_]``.
The only exception is  the generic ``N[expr_,prec_,OptionsValue[]]`` associated to the Builtin ``N``, which are necessarily not a `NValues` rule.
``N[expr, prec, Method->method]`` establishes the preferred method, by storing it in the queue property `_preferred_n_method` of the `Evaluation` object.
=> Fix n method (issue #137)

CHANGES.rst, mathics/builtin/comparison.py, mathics/core/atoms.py
* Simplify SameQ logic for MachineReal
* Hook comparison operators into documentation
* Fill out description and examples for SameQ
Note: comparison.py probably should be split out into its own subsection
As always, with regards to documentation, and sectioning there is a lot more there to  do.
=> SameQ tweaks -

test/test_calculus.py
One of the ideas about how to speed up certain evaluations in Mathics would be to try to send to sympy complete expressions instead of doing several steps of partial conversions in the evaluation loop. 
The risk of doing it is that it could break the expected evaluation logic in WL. Here I propose some tests to detect this kind of bugs.
=> sanity test to pass in a more aggressive sympy translation

mathics/algorithm/parts.py, mathics/core/atoms.py, mathics/core/expression.py, mathics/core/subexpression.py
Side Note: Tracing Add[1, 2] seems to do a lot of unnecessary data motion and conversion back and forth.
We convert to from a tuple to a list, evaluate elements that are already in their reduced form, try to flatten a flattened list convert that into a Mathics Sequence only to convert it back to something like what it was before. 
The lack of comments/commentary about what is done and why and lack of modularity (which I really still don't know how to deal with) just is obscuring this convoluted process. Sure, in some cases it needs to be this complex. Just not _all_ of the time.
=> leaf -> element more places

CHANGES.rst, mathics/builtin/inout.py, mathics/core/definitions.py, mathics/core/evaluation.py, mathics/core/expression.py, mathics/core/symbols.py
Trying to understand the problem in #154, I realized that it would be useful to record how long each evaluation step takes, so here is a PR that implements that.
=> timing TraceEvaluation

mathics/core/atoms.py, mathics/core/expression.py
Small stuff.
With respect to `get_head_name()` this is in the class hierarchy and does the right thing (use the class name) for all of the functions removed. This function seems to be used mostly in `has_form()` but right now doesn't seem to be used very much. 
I did check that the custom functions give the same result as when they are removed.
With respect th threading, note the fact this has to do with expression transformation and is _not_ optional (as it would be for hardware threading).  Alas, right now don't do any sort of Python/OS threading so which seems to be what a large part of the motivation in the language for adding this.
=> Clarify "threading" in Exprs. DRY Numeric classes

mathics/core/atoms.py
This is a much less drastic version of #49. This just makes that in `from_python`, the case of  Mathics expressions are tested as the first case.
=> rearrange from_python to first try if the argument is a BaseExpression

mathics/algorithm/optimizers.py, mathics/builtin/base.py, mathics/builtin/files_io/files.py, mathics/builtin/numbers/calculus.py, mathics/builtin/patterns.py, mathics/core/atoms.py, mathics/core/convert.py, mathics/core/evaluators.py, mathics/core/expression.py, mathics/core/subexpression.py, mathics/core/symbols.py
And lastly reorder methods in the Expression class alphabetically. 
@mmatera since you asked about this, here is how this was useful in the PR alone. 
I wanted to know which methods of BaseElement are also listed in Expression. Those that are candidates for moving into Atom.
Having these two sets of methods sorted alphabetically made it possible for me to detet this.
=> BaseExpression -> BaseElement, move some methods out of BaseExpression (into Atom)

mathics/core/definitions.py, mathics/core/element.py, mathics/core/evaluation.py, mathics/core/expression.py, mathics/core/pattern.py, mathics/core/rules.py, mathics/core/symbols.py
As stated before, this is most important part of what I wanted to do in the refactor. Although I wanted to do it first, alas it had to come after all of that other more disruptive stuff. 
So with this, I am done doing major refactoring and when I pick this up again will focus on adding properties to an the elements part of an Expression. Which was a digression of I forget what, improving interpreter evaluation performance? 
But even though I am more or less stopping the refactoring part here, there is still a lot more to do, by far. If others are interested please keep going. 
In particular, there are a number of methods in BaseElement that really shouldn't be there. They should either be moved into the subclasses that import BaseElement, or put in a Mixin class like NumericOperators, or …
=> Move BaseElement into mathics.core.element

mathics/builtin/inout.py, mathics/core/element.py, mathics/core/expression.py
unformatted was used only in 1 place, and seems it works without it there.
I think that now the `__new__` method can be converted to a `__init__`, fixing the garbage collection problem.
=> Remove unformatted property from BaseElement

mathics/core/atoms.py, mathics/core/element.py, mathics/core/expression.py, mathics/core/symbols.py
Following up on @TiagoCavalcante ' s comment about (most) Atoms, especially Strings not being needing re-evaluation (or a complex cache) I have reduced this at the slight expense of an extra check in one of the caching routines.
That could be removed by fixing up BaseElement not to set up a cache in the first place (which I think is the right thing), but there is some other interaction with Boxing that is causing infinite recursion. Go figure. 
Until we get that problem fixed (and will that lead to some other unrelated place that needs to change as well?) in my opinion the best thing is just to make that extra lightweight test in the cache update routine. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/187"><img …
=> Reduce atom has changed

mathics/builtin/base.py, mathics/builtin/box/graphics.py, mathics/core/atoms.py, mathics/core/element.py, mathics/core/evaluation.py, mathics/core/expression.py, test/test_custom_boxconstruct.py, test/test_format.py, test/test_formatter/test_svg.py
This PR follows #184: includes several comments on ``mathics.core`` and basic changes in  ``mathics.builtin.__init__`` and ``mathics.builtin.base`` to clarify and improve the implementation of ``BoxConstruct``. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/185"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Pre Rework BoxConstruct

mathics/core/definitions.py, mathics/core/element.py, mathics/core/expression.py, mathics/core/symbols.py
has_changed() is now either uncertain_final_value(), called in do_format()
or uncertain_final_definitions(), called in evaluate().
Document what these do, and motivate why specific constant values are
returned in specific classes.
Having the same name for two slightly different things was confusing.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/192"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Clarify function previously called "has_changed()"

CHANGES.rst, mathics/builtin/assignments/clear.py, test/test_assignment.py, test/test_numericq.py
Fix #194 by cleaning the definitions cache for the corresponding symbol.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/195"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> clear the cache of the definition for the symbol to be cleared

mathics/builtin/comparison.py, mathics/builtin/drawing/plot.py, mathics/builtin/graphics.py, mathics/builtin/numbers/algebra.py, mathics/builtin/options.py, mathics/builtin/string/operations.py, mathics/builtin/structure.py, mathics/core/element.py, mathics/core/expression.py, mathics/core/symbols.py, test/test_elements/test_flatten_head.py
Remove **kwargs in init/new methods when they aren't used. At the lowest level if `**kwargs` isn't used, it should not be tolerated (as opposed to tolerated and ignored). Instead, callers should need to know what is accepted in construction and not have arbitrary stuff accepted and ignored.
More leaf/leaves to element/elements conversions.
Go over `flatten_with_respect_to_head()`:  
*  `flatten` -> `flatten_with_respect_to_head()` when that's what it means. Other `flatten()` methods which work slightly differently haven't been touched.
* a small unit test started for flatten_with_respect_to_head was started.  Expect more unit tests of elements in the future
Some minor bugs encountered were fixed.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/196"><img …
=> Another cleanup round

mathics/builtin/comparison.py, test/test_compare.py
Move unit tests out of class docstring into test_compare. Go over documentation for Equal, Less, Greater
I am pleased to see that we have now advanced to the level where we can fully remove those non-document tests fully out of docs where it never belonged since we now have the technology in place to this the right and normal way.
Now what remains is a lot of cleanup work (partly made worse because we pushed using incorrect technology rather than fix the technology)
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/211"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Docs/tests for Equal, Unequal, Less, Greater

mathics/algorithm/parts.py, mathics/builtin/arithfns/basic.py, mathics/core/element.py, mathics/core/expression.py
Remove _cache property from Element and clear_cache method from ``BaseElement``, and move them to the class ``Expression``. These properties do not make sense for Elements that do not have sub-elements. Also, I added a couple of *ifs* 
to check that calls to ``clear_cache`` in builtins are performed just over expressions.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/218"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Removing Expression "cache" from BaseElement.

mathics/docpipeline.py
$TestTracing was failing on the Django side. Here we
sync up code a little bit.
Ideally though, we would put more of this in the common routine.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/219"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> doctest handling of "..." again

.github/workflows/osx.yml, .github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, mathics/core/parser/parser.py, test/test_parser/test_parser.py
`test_parser.py` has been failing for me for a while. Apparently ever since in mathicsscript we added these alternate standard Unicode symbols for some custom Wolfram ones.
Here we adapt tests where unicode symbols have been bleeding cause failures in parser testing because it expect no unicode characters. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/220"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Tolerate Unicode in parser testing

mathics/builtin/__init__.py, mathics/builtin/compilation.py, mathics/builtin/numbers/calculus.py, mathics/builtin/numbers/constants.py, mathics/builtin/numbers/diffeqns.py, mathics/builtin/physchemdata.py, mathics/builtin/quantities.py, mathics/builtin/recurrence.py, mathics/builtin/specialfns/gamma.py, mathics/builtin/specialfns/othogonal.py, mathics/builtin/string/regexp.py
This PR starts fixing the lack of summary_text  on many of the builtins symbols. I also included a few lines that allow activating a sanity check verifying that this attribute is set on all the built-in classes.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/222"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Adding summary text

mathics/builtin/__init__.py, mathics/builtin/matrices/__init__.py, mathics/builtin/matrices/partmatrix.py, mathics/builtin/tensors.py, setup.py
I tried to implement Diagonal and it seems working.
In https://github.com/Mathics3/mathics-core/issues/115 is proposed to use native Wolfram Language, but I hope this it will be sufficient, at least for the moment.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/215"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add builtin Diagonal

mathics/format/asy.py, mathics/format/svg.py
Currently we give a traceback and error exit. A workaround for issue #224
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/226"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Tolerate not-implemented errors in graphics

mathics/builtin/files_io/importexport.py, mathics/core/parser/convert.py, test/test_importexport.py, test/test_parser/test_convert.py
This PR fixes the following behaviour
```
In[1]:= StringForm["Text1\\n Text2"]
Out[1]= Text1
Text2
```
```
In[1]:= StringForm["Text1\\n Text2"]
Out[1]= Text1\n Text2
```
Some character encoding related bugs have been fixed. In particular `Export` did not honor the `CharacterEncoding` option.
=> Use python built-in functions to escape strings

mathics/builtin/files_io/files.py, mathics/core/read.py
`InputFileName` was broken since 3e3802797677bdf075dfd92f3680c2c6a60055b3, because `INPUTFILE_VAR` is updated in another file.
=> Fix InputFileName

mathics/builtin/matrices/constrmatrix.py, mathics/builtin/matrices/partmatrix.py, mathics/builtin/tensors.py, test/test_constrmatrix.py
Move a `#>` test into a unit test and Moved DiagonalMatrix and IdentityMatrix to group Matrices and Linear Algebra from @adamantian
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/229"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Reorganize builtins

mathics/builtin/pymimesniffer/magic.py
Deprecated aliases have been removed in python/cpython#28268
=> Use assertEqual instead of assertEquals for Python 3.11 compatibility.

mathics/builtin/numbers/algebra.py, test/test_algebra.py
This PR fixes issue #214, by catching the exception. In the future, we can prevent the exception for this particular case, but still would appear in other cases.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/238"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Handle unexpected SymPy exceptions in `Simplify[]`

mathics/builtin/numbers/constants.py
This is just the part of #237 associated with mathematical constants
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/239"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> summary_text in mathics.builtin.numeric.constants

mathics/builtin/list/eol.py, mathics/builtin/numbers/algebra.py
This PR adds the ``summary_string`` field to ech ``Builtin`` in this module.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/249"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> adding summary texts in builtin.numeric.algebra

mathics/builtin/numbers/calculus.py, mathics/builtin/numbers/exptrig.py, mathics/builtin/numbers/integer.py, mathics/builtin/numbers/linalg.py, mathics/builtin/numbers/numbertheory.py
This PR adds ``summary_text`` to all the ``Builtin`` in the module, except ``mathics.builtin.numbers.algebra`` that goes in a different PR. I tried to follow the WR style.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/248"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Summary numbers

mathics/builtin/numbers/algebra.py
This continues the fix PR #232 to the `Cancel` function, which made use of the same code.
Without it Mathics crashes from this input
`In[1]:= a == d b + d c // Factor`
=> Fix sympy_factor to allow equalities

mathics/builtin/base.py, mathics/core/evaluation.py, mathics/core/expression.py, mathics/core/rules.py, test/core/test_elements_properties.py, test/core/test_flatten_head.py
Track properties of a compound expression: 
* whether the expression is flat
* whether we know the expression to be sorted (a false value includes "don't know if sorted")
* whether we know the expression to be fully evaluated (see caveat above)
In addition we start to mark Box elements as "literal" - that is, the are indivisible from the standpoint of evaluation and you don't "evaluate" these. Instead I guess we run a format-type evaluation method. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/264"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Expression elements properties

mathics/builtin/box/graphics.py, mathics/builtin/box/graphics3d.py, mathics/builtin/box/uniform_polyhedra.py, mathics/builtin/colors/color_directives.py, mathics/builtin/drawing/graphics_internals.py, mathics/builtin/graphics.py
From the @rocky comment in #261, I realized that the current implementation of this class and their daughters was wrong and misleading. This PR fixes this and partially fix the way in which the documentation is generated. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/278"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> _GraphicsElement -> _GraphicsElementBox / _GraphicsDirective

CHANGES.rst, mathics/builtin/assignments/internals.py, mathics/builtin/scoping.py, mathics/core/definitions.py, test/builtin/test_assignment.py, test/helper.py, test/test_context.py, test/test_format.py
This PR fixes the behavior of assignments to Message in protected symbols. Also, pytests in ``pytest_context.py`` where improved to check the compatibility with the WMA behavior.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/283"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Contexts and message assignment

mathics/builtin/list/constructing.py, mathics/core/atoms.py, mathics/core/element.py, mathics/core/expression.py, mathics/core/rules.py, mathics/core/symbols.py, test/core/test_elements_properties.py, test/core/test_expression_constructor.py, test/format/test_svg.py
@mmatera In #277 the property recalculation of elements properties and avoidance of calling `to_python()` was removing by virtue of called the setters property. Also, we weren't making use the flat property that was fixed as a result of #277. 
This preserves those properties and allows Expression creation to give (some of) these properties. To be added could be  add a way to indicate that `to_python()` on elements isn't needed. 
What could be done is to go over all calls to `Expression` to see if we can specify whether we can avoid calling `to_python` and if we determine element properties and set them up front.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/281"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> avoid Expression.element recalculation if possible

CHANGES.rst, mathics/builtin/arithmetic.py, mathics/builtin/box/graphics.py, mathics/builtin/box/graphics3d.py, mathics/builtin/distance/stringdata.py, mathics/builtin/drawing/image.py, mathics/builtin/drawing/plot.py, mathics/builtin/files_io/files.py, mathics/builtin/files_io/filesystem.py, mathics/builtin/files_io/importexport.py, mathics/builtin/inference.py, mathics/builtin/list/eol.py, mathics/builtin/list/rearrange.py, mathics/builtin/lists.py, mathics/builtin/logic.py, mathics/builtin/numbers/calculus.py, mathics/builtin/patterns.py, mathics/builtin/procedural.py, mathics/builtin/structure.py, mathics/core/element.py, mathics/core/expression.py, mathics/core/symbols.py, test/test_hash.py
Following in the direction of looking a simpler and clearer interface for core.BaseElements, in this PR the use of `is_true()` was completely removed. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/294"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> By by is true

CHANGES.rst, mathics/builtin/system.py
In WMA, the command  ``Share[]`` tries to recover memory by replacing repeated expressions by references to a single instance of the expression. For example, if we have two definitions
```
In[1]:= table=Table[i^2,{i,1000}];                                              
In[2]:= a=F[table,2];                                                           
In[3]:= b=F[table,3];                                                           
In[4]:= MemoryAvailable[]                                                       
Out[4]= 9147990016
In[5]:= Share[]                                                                 
Out[5]= 17104
``` 
in a way that 17104 bytes are recovered by replacing (internally) the three lists in the definitions of `table`,`a` and `b`  by a single list expression, that is …
=> improving Share[] 

mathics/builtin/assignments/assign_binaryop.py, mathics/builtin/assignments/assignment.py
This just uniformizes the format of the docstrings.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/280"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> cleaning docstrings in assignment symbols

mathics/builtin/arithmetic.py, mathics/core/element.py
not an int argument. This will be required in the future for
Expression() - otherwise use to_expression().
One more place leaves -> elements.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/296"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> create_infix calls Expression() with Integer ..

mathics/builtin/numbers/algebra.py
Have to hold off on the Range conversion problem until I have time to figure out what's wrong
<strike>
Check this out.
Using Python list comprehension with range:
```
In[1]:= Timing[Range[1000]][[1]]
Out[1]= 0.00679923
```
Previous method:
```
In[1]:= Timing[Range[1000]][[1]]
Out[1]= 0.0269802
```
</strike>
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/297"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Range speedup and One more Expression() conversion

mathics/builtin/colors/color_directives.py, mathics/core/systemsymbols.py
The additional systemsymbols are mostly used in builtin/arithmetic.py which I'll use in a future PR. I though many of these like Apply are general enough to be here.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/301"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Make a pass over color_directives + more symbols..

mathics/builtin/files_io/files.py, mathics/builtin/files_io/filesystem.py, mathics/builtin/files_io/importexport.py, mathics/core/read.py, mathics/core/streams.py, test/builtin/colors/test_colors.py, test/builtin/files_io/test_files.py
Add a number of `DeleteFile[]`'s into the doc tests. 
Isolate and separate stream close. 
Move test_files.py to its proper place in the test hierarchy
Fixes #309
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/310"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Remove more temporary files created in testing, make a pass over the I/O code

CHANGES.rst, mathics/builtin/arithfns/basic.py, mathics/builtin/list/constructing.py, mathics/builtin/numbers/numbertheory.py, mathics/core/element.py, mathics/core/evaluators.py, mathics/core/expression.py, mathics/core/rules.py, setup.py, test/core/test_elements_properties.py, test/core/test_expression_constructor.py
ElementsProperties is a mutable record.
Note that addition work is needed to categorize existing Expression() calls into `to_expression()` or
`Expression()`.
After that is done, we should see a big improvement in speed due to a
reduction of unneeded calls to convert elements.
Also, there should be improvements as we start setting the elements
properties in the calls to be more precise.
Until then, the performance here will be slightly worse with this
commit, since we have the worst of both worlds: we have to do conversion
on each Expression() call as well as conversion that may already be done in setup to calling
Expression which will be required (not optional) in the future.
A specialization of Expression, ListExpression() will be using this as the base code to work off of.
<a …
=> Revise Expression to use ElementsProperties

mathics/core/rules.py, mathics/core/symbols.py
This PR removes two superfluous methods from the `Atom` interface and a superfluous call to them.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/321"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> removing flatten_x_sequence from Atoms and subclasses

test/test_doc.py
This PR tries to reinforce that new built-in symbol classes that are going to be added to master be minimally documented. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/343"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Pytest to check documentation in new builtin classes

mathics/core/expression.py, test/test_evaluation.py
@rocky, this PRs adds the test case that shows the issue with ``Unevaluated``. I marked it as xfail. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/344"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> adding test for Unevaluated over symbols

mathics/core/expression.py
Some small bugs in setting/preserving elements_properties found in benchmark tests
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/349"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Preserve elements_properties

mathics/algorithm/integrators.py, mathics/builtin/numbers/calculus.py, mathics/builtin/optiondoc.py
This PR fixes a few bugs I found in ``NIntegrate`` trying to make it works when scipy is not available. Also, I marked here ``NIntegrate``, and ``_BaseFinder`` daughter classes as builtin that requires scipy, to avoid running their doctests when scipy is not available (because the results are going to be slightly different).
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/363"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fixing NIntegrate to make the internal integrators available.

CHANGES.rst, mathics/algorithm/optimizers.py, mathics/builtin/numbers/calculus.py, test/builtin/numbers/test_nintegrate.py, test/test_nintegrate.py
* NIntegrate[] no longer requires scipy.
* There were a number of small changes/fixes involving NIntegrate.
* NIntegrate tests have been expanded and unit test moved under `test/builtins/numbers`
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/374"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Revise Nintegrate to allow scipy to be optional

mathics/builtin/scipy_utils/optimizers.py, mathics/doc/common_doc.py
This has the last changes. In a different PR I will try to remove the code of pymathics in commondoc.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/377"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> trailing changes

mathics/builtin/assignments/assignment.py, mathics/builtin/assignments/internals.py, mathics/builtin/evaluation.py, test/builtin/test_assignment.py
In particular:
* process_assign_recursion_limit
* process_assign_iteration_limit
* process_assign_module_number
only take 3 args, not 6
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/388"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix fn call mismatches in process_assign_other

.github/workflows/osx.yml, .github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, setup.py
Note that for Pyston this slow things down.
For PyPy we can't use it either.
There is benefit in doing this over CPython (probably up to 3.9), but
since it takes minutes to run Cython, for development this often isn't a
big win since it can happen that files you are working on change and so you'll need to
run again, with the 2 minutes again. Or files will stale, sometimes
inadvertently.
So running Cython is worth the effort before building a
wheel (i.e. before release) or using in a docker container.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/398"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Reverse Cython default.

mathics/builtin/arithfns/basic.py, mathics/builtin/assignments/internals.py, mathics/builtin/base.py, mathics/builtin/inout.py, mathics/builtin/numbers/algebra.py, mathics/builtin/numbers/integer.py, mathics/builtin/patterns.py, mathics/core/definitions.py, mathics/core/expression.py, mathics/core/pattern.py, mathics/core/subexpression.py
and more replacements from `leaves` to `elements`.
The nontrivial changes are essentially those proposed in the first patch in #400.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/401"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Removing conversions from Expression.__init__

mathics/core/expression.py
This PR fixes the issue that screwed the sorting property and made test_series.py fail.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/403"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix build element properties in Expression.__init__ and Expression.rewrite_apply_eval

mathics/core/list.py
* avoid building properties in the List constructor
* rewrite_apply_eval keeps `self` untouched, and returns a new object if the elements must be reevaluated.
Here there is a comparison between master and this branch for the combinatorial benchmark.
Pyston 2.3.4 (3.8.12)
NO_CYTHON=1
using SymPy 1.8, mpmath 1.2.1, numpy 1.21.4
|   test                                        |   master           |   #404            |
| --------------------------------------------- | ------------------ |------------------ |
| load_combinatorica 				|   179.93 ms        |  181.15 ms        |   
| test_permutations_1_1   		       	|   932.17 ms	  | 	930.90 ms   	 |
| test_permutations_groups_1_2   		|   5801.66 m	  | 	5642.51 ms  	 |
| test_inversions_and_inversion_vectors_1_3   	|   667.19 ms	  | 	530.34 ms …
=> Improve the implementation of mathics.core.list

mathics/builtin/files_io/files.py, test/builtin/files_io/test_files.py
Put more testing inside pytest and remove from doctest.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/409"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Reduce temp file garbage in Close doctests

mathics/format/asy.py
This is part of a bigger plan to go over little bugs that are noticeable before release.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/415"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Strip '\n[ ]+' which confuses mathicsscript asy

mathics/builtin/__init__.py, mathics/builtin/assignments/assign_binaryop.py, mathics/builtin/drawing/image.py, mathics/builtin/list/constructing.py, mathics/builtin/lists.py, mathics/builtin/numbers/constants.py, mathics/builtin/numbers/exptrig.py, mathics/builtin/numbers/linalg.py, mathics/builtin/vectors/__init__.py, mathics/builtin/vectors/constructing.py, mathics/builtin/vectors/mathops.py, mathics/builtin/vectors/vector_space_operations.py, mathics/core/convert/matrix.py, mathics/core/convert/mpmath.py, mathics/core/convert/sympy.py, setup.py
This code keeps the vector split from #418 but remove the sorting part.
Something in the sorting part of #418 causes testing slow down  a lot, like several minutes in `Plot[]` routines like `Plot[KelvinKer[x]]` and `Plot[KlevenKei[x]`
I don't believe it is the code in the sorting tests that is a problem, but instead more a latent performance problem in our code base that sorting happens to trigger.  Until this is isolated and fixed, I am reverting this for now.  There will be a separate PR in the future to reinstate this after the problem is more thoroughly isolated. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/420"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add vector section but revert test (and chapter) sorting for now.

.editorconfig, CHANGES.rst, mathics/builtin/arithfns/basic.py, mathics/builtin/arithmetic.py, mathics/builtin/intfns/combinatorial.py, mathics/builtin/intfns/recurrence.py, mathics/builtin/numbers/constants.py, mathics/builtin/numbers/exptrig.py, mathics/builtin/specialfns/bessel.py, mathics/builtin/specialfns/expintegral.py, mathics/builtin/specialfns/orthogonal.py
and generalize `_MPMathFunction` `nargs` to allow a set of acceptable arguments
@TiagoCavalcante every time I encounter the attribute bitset it feels to me that those should be capitalized to make it more clear that this is a constant and a bitmask. 
If it okay to make the change throughout, I'll do that in a separate PR.  
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/424"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add BernoulliB

mathics/doc/common_doc.py
until we understand why this causes testing time to increase significantly
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/426"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Rever test execution sorting for now

CHANGES.rst, mathics/builtin/procedural.py, test/builtin/test_procedural.py
Before:
```
In[1]:= NestWhile[Total[IntegerDigits[#]^3] &, 5, UnsameQ, All]
Traceback (most recent call last):
File "/home/temp/mathics-core/mathics/core/rules.py", line 214, in do_replace
return self.function(evaluation=evaluation, **vars_noctx)
File "/home/temp/mathics-core/mathics/builtin/procedural.py", line 681, in apply
test_elements = results[-m.value :]
AttributeError: 'Symbol' object has no attribute 'value'
...
...
File "/home/temp/mathics-core/mathics/core/rules.py", line 214, in do_replace
return self.function(evaluation=evaluation, **vars_noctx)
File "/home/temp/mathics-core/mathics/builtin/procedural.py", line 681, in apply
test_elements = results[-m.value :]
AttributeError: 'Symbol' object has no attribute 'value'
```
After:
```
In[1]:= NestWhile[Total[IntegerDigits[#]^3] …
```
=> Fix crash in NestWhile when supplying "All" as the fourth argument, add more examples, and add some test cases

mathics/builtin/atomic/symbols.py, mathics/builtin/scoping.py, mathics/core/definitions.py
Bug fixed in using a string attibute name for its value.
Runing doctests changing module numbers should not be done.
Also don't run pytest kinds of tests in doctest. A pytest should be
written here.
I fear the entire module was disabled because too many of the tests were flaky.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/432"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Reinstate documenting "Scoping Constructs"

Makefile, mathics/doc/common_doc.py, mathics/doc/tex/Makefile, mathics/docpipeline.py
Makes mathics.pdf look a little more organized.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/439"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Sort chapters and sections in pdf doc

CHANGES.rst, mathics/builtin/drawing/image.py, mathics/core/element.py, mathics/core/expression.py, test/core/test_expression.py
This PR fixes #446, providing a canonical sort key to `Image` atoms.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/448"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add sort Key for `Image` type

mathics/core/element.py, mathics/core/expression.py
It so happens `get_sort_key()` also comes up in the pymathics graph module I have been working to get fully converted. 
I spent a little more time then to try to understand this, and describe it.
=> Yet another pass over describing "get_sort_key()"

mathics/core/definitions.py, mathics/core/evaluators.py, mathics/doc/common_doc.py, mathics/docpipeline.py, test/builtin/numbers/test_nintegrate.py
This doesn't fully work but it is a step in the right direction.
The context for pymathics modules should have the Pymathics module name, e.g. `Pymathics``Graph` or `Pymathics``Natlang`` rather than simply `Pymathics`.
But this messes up both testing and interactive use.
@mmatera if you can move this forward that would be good. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/453"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add pymathics to docs

test/builtin/numbers/test_calculus.py
This PR adds some tests for `Integrate`, that were reported to fail in  #346. In my system, the tests are passed without problems.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/461"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> adding tests for 346

CHANGES.rst, mathics/builtin/arithfns/basic.py, mathics/builtin/inout.py, mathics/builtin/recurrence.py, test/builtin/test_comparison.py
This PR fixes formatting  issue in ``Power`` that was behind the one reported in #332.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/460"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add parentheses around negative numbers in formatting output in infix notation - issue 332

CHANGES.rst, mathics/builtin/drawing/image.py, mathics/builtin/numbers/algebra.py, mathics/builtin/numbers/calculus.py, mathics/core/expression.py, test/core/test_expression.py
This PR fixes #458.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/467"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix get_sort_key to reproduce the canonical order in WMA

mathics/builtin/base.py, mathics/builtin/specialfns/elliptic.py
This PR adds a warning if the `Elliptic*` builtins receive a wrong number of parameters.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/472"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> adding controls for the number of arguments

mathics/builtin/atomic/strings.py, mathics/builtin/intfns/combinatorial.py, mathics/builtin/specialfns/__init__.py, mathics/builtin/specialfns/bessel.py, mathics/builtin/specialfns/elliptic.py, mathics/doc/common_doc.py
This PR really has to separable things. The first part is to allow text links in url. The lack of this I found annoying and it is a direct result of a homegrown implementation that is hard to understand as well as being incomplete.
Because there are substitutions going on various places, I couldn't use either double quote which gets substituted in HTML for &quote) or single quote which is interpreted as code. Vertical bar is used in regexps and escaping that makes this ugly re even more ugly. So I used colon. 
The second aspect of this PR has to do with the builtins. The thought is on each builtin start of with the corresponding Wikipedia name if one exists with this name linked to the corresponding wiki page, and then give Sympy (when appropriate) and WMA links. 
Again we are hamstrung …
=> Allow text link in URL

mathics/format/asy.py, test/format/test_asy.py
this caused the Dice example in the manual to fail - it uses rectanglebox.
Also, add type annotations on functions.
I think when one of the opacity parameters was added not all of the routines were adjusted. And we didn't have a test to check this either.
We have a test now.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/485"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Correct  order of parameters in asy rectanglebox ..

CHANGES.rst, mathics/autoload/rules/GudermannianRules.m, mathics/builtin/numbers/exptrig.py, mathics/builtin/numbers/hyperbolic.py, mathics/core/atoms.py
Add Gudermannian from autoload Guidermannian.m
Exponential functions should also be split from Trig functions. And both gone over. But that is for some other time. 
All of this could have the URLs gone over.
This is going to be the last of the url and doc improvements before 5.0.1
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/491"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Split off hyperbolic functions from trig fns..

mathics/algorithm/clusters.py, mathics/builtin/numbers/hyperbolic.py, mathics/core/expression.py, mathics/core/rules.py, mathics/core/util.py, mathics/timing.py
* `robust_min()`: is used only one place. Move this function there
<strike>*  `IS_PYPY`: move to `mathics.system_info`</strike>
* timing routines: move to `mathics.timing` module
* `function_arguments()`: We had more complex to support older Pythons which we don't support anymore. Move code to `rules.py` where it is the only place it is used.
The parts removed will be separated into another PR.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/495"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Move timing out of `mathics.core.crunch_util`

CHANGES.rst, mathics/builtin/vectors/math_ops.py, test/builtin/atomic/test_numbers.py, test/builtin/atomic/test_strings.py, test/builtin/vectors/test_mathops.py
This is in preparation ofr adding Builtin Curl which is going to be used
as a tutorial example.
Norm:
* Remove vector restriction on parameter m when parameter p not specified.
* Pull out its unit tests, and expand on the doctess
* Start pulling out eval methods here too.
* Allow "Frobenius" in parameter p
Some small test doc typos corrected.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/504"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Go over Cross and Norm

mathics/builtin/numbers/calculus.py, mathics/core/element.py, mathics/core/evaluation.py, test/builtin/numbers/test_calculus.py, test/builtin/test_comparison.py
Also:
remove overloaded type-changing variable
reduce vaguess in vargueness "msg" - is what message message back from
evaluation? message given on assertion failure? Some other kind of message?
Fixes #502 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/503"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Correct D[] bug in passing wrong parameter type

mathics/core/expression.py, mathics/core/list.py
* Better ListExpression literal detection
* Allow [] access to ListExpression's
* Better formatting of ListExpressions:
* str() gives a longer form
* repr() limits to reprlib.repr limits (30 characters)
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/505"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> ListExpression class changes

mathics/algorithm/parts.py, mathics/builtin/list/eol.py, mathics/core/expression.py, mathics/core/list.py
When I was revising ListExpression  a while ago, this code looked like it was preventing simpler ListExpression tests. (See below)
Now I am not totally sure. It fixes a potential bug if Part somehow is not able to transform an `Expression` into `ListExpression`, and if in the future we need to transform `Expression` into some other kind of specialized expression.  
Via testing t am not seeing this right now. 
I have made some slight changes to the code so as to hopefully make it easier to understand and modify should we need to in the future. 
Hopefully this will pave the way for simplifying  and replacing `expr.has_form("List", None)` with `isinstance(expr, ListExpression)` possibly after a few other parts of the code are gone over.
<a …
=> Revise `set_part()` to be more functional

mathics/algorithm/parts.py, mathics/core/parser/convert.py, test/test_custom_boxconstruct.py
Go over parser/convert  and have it create ListExpression for list expressions
Try to make parser/convert less confusing by using more traditional Python practice, and add type annotations.
Do  our first has_form("List", None) removal. Many more will follow, but additional ListExpression cleanup is needed first.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/508"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> More list expressions

mathics/core/convert/expression.py, mathics/core/expression.py, mathics/core/formatter.py, mathics/core/structure.py
Here we eliminate most of the uses of  `Expression(SymbolList, ...)` 
However something involving UnlinkedStructure will cause test failures, so Expression is kept there for List, for now.
LInkedStructure and Unlinked structure have been split off into its own module. 
Some small stylistic cleanup done on Expression.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/516"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Use ListExpression where appropriate

admin-tools/normalize_docstrings.py, mathics/builtin/arithmetic.py, mathics/builtin/attributes.py, mathics/builtin/comparison.py, mathics/builtin/inout.py
Previously, @rocky had noticed that among many other things,  tags in  ``__docstring__``  are not properly indented.  This PR adds a basic tool for start fixing this ubiquitous issue.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/521"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> adding a tool for normalize the indentation in docstrings

mathics/builtin/arithmetic.py, test/builtin/arithmetic/test_abs.py
I was looking at https://github.com/axkr/symja_android_library/blob/master/symja_android_library/rules/AbsRules.m to see if we have things covered that are listed there. Nope.
This PR doesn't do it either, but at least I've noted what is needed.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Go over Abs[]

mathics/builtin/arithmetic.py, mathics/builtin/numbers/constants.py
Fixes #514
The first commit in the PR will be another example in the developer's doc for how to add a builtin. 
This one (even though it was done last) is in fact the is the simplest and simplest to explain. 
After that in the doc will be KroneckerProduct (for Arrays not vectors). This too will link to a specific commit in the code for reference. 
and finally there will be a Curl example (not finished yet even in code). 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/517"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add Undefined value

mathics/builtin/vectors/vector_space_operations.py
Initially I thought I wouldn't be able do this because I was not aware of `to_sympy_matrix()`.
This currently has problems handling vectors, and doesn't have a unit test. But this is possibly good enough for a phase 1 introduction for how to write a Mathics builtin, 
See https://mathics-development-guide.readthedocs.io/en/adding-kroneckerproduct/extending/developing-code/extending/KroneckerProduct/basic-skeleton.html  which will be revised soon. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/511"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> KroneckerProduct for developer's tutorial

CHANGES.rst, mathics/algorithm/parts.py, mathics/builtin/base.py, mathics/builtin/box/graphics.py, mathics/builtin/box/graphics3d.py, mathics/builtin/box/layout.py, mathics/builtin/colors/color_directives.py, mathics/builtin/graphics.py, mathics/builtin/inout.py, mathics/builtin/makeboxes.py, mathics/builtin/patterns.py, mathics/builtin/string/operations.py, mathics/core/atoms.py, mathics/core/element.py, mathics/core/formatter.py, mathics/core/symbols.py, mathics/format/mathml.py, mathics/format/tex.py, mathics/format/text.py, test/format/test_format.py
This is the second cut of #492. 
In this round, 
* the interface of boxes_to_* was reformulated to be more scalable. 
* The `inout.py` module was splitter in parts closer to the WR organization.
*  `_BoxedString` was removed in favor of using a `StyleBox` construct, which is simpler.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/515"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=>  Tyding up formatting. Second round.

test/test_duplicated.py
During the last months, we devoted some time to reorganizing and splitting the modules under builtin. One consequence was that accidentally, some symbols could result in duplications along different modules. This PR fixes the cases I found, and adds a pytest to check that subsequent reorganizations do not produce more duplications.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/522"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Controlling symbol duplication

mathics/builtin/numbers/calculus.py, mathics/core/symbols.py, test/builtin/numbers/test_calculus.py
* Sort classes in calculus alphabetically
* add URL links to `Solve`
* remove variable type changing assignment in `Solve`
* note problem with filtering out domain in rule in `Solve`
* one small annotation addition
* Move `Solve` unit tests in docstring to unit tests
* move to flag-style attribute naming on `calculus.py`
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/529"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Tidy `Solve` and `calculus.py` a little

mathics/builtin/atomic/numbers.py, mathics/core/atoms.py, mathics/core/convert/mpmath.py, mathics/core/convert/python.py, mathics/docpipeline.py, mathics/main.py, mathics/timing.py
and mathics via a new function in mathics.timing.
TODO: add to mathicsscript and Django.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/538"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add --show-cache-statistic option to docpipeline

CHANGES.rst, mathics/builtin/vectors/math_ops.py
This is intended to match text in the development guide.
It might be interesting to expand Curl to handle those all four forms, but this is right, but this requires more skill than I can easily handle.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/535"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add 2d and 3d vector forms of Curl

CHANGES.rst, mathics/core/parser/convert.py, mathics/doc/documentation/1-Manual.mdoc, test/core/parser/test_convert.py
In WL, ```n`p``` represents a number `n` with precision  `p`, which means that the number is defined up to an error `dn ~ n * 10^-p`. In particular, in WMA and in Mathics,
```
In[1]:=0.`5
```
is parsed as ```Out[1]=0.x 10^-5```. On the other hand, in WMA,  ```0`5``` (without the decimal point) is parsed as `0` (an `Integer`), but in the current master of Mathics, it is parsed also as   `0. x 10^-5`. This PR changes this behavior to make it compatible with the expected in WMA. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/546"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Use Integer 0 when we have a relative precision of the value 0

mathics/builtin/arithfns/basic.py, mathics/builtin/arithmetic.py, mathics/builtin/atomic/numbers.py, mathics/builtin/atomic/strings.py, mathics/builtin/atomic/symbols.py, mathics/builtin/attributes.py, mathics/builtin/base.py, mathics/builtin/comparison.py, mathics/builtin/specialfns/elliptic.py, mathics/core/atoms.py, mathics/core/convert/expression.py, mathics/core/element.py, mathics/core/expression.py, mathics/core/list.py, mathics/core/symbols.py, mathics/timing.py, test/core/test_expression_constructor.py, test/core/test_is_literal.py
Although there may be benefit in noting literals that do not have direct
Python representations like Complex (as it currently is implemented) or
Boxes, the vast majority of literals that we can make immediate use of
is where there is a direct Python representation, e.g. Integers, Reals,
Strings, and ListExpressions (of literals).
Also go over some types and remove some string.get_string_value()
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/537"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Start to go over literals

mathics/core/element.py, mathics/core/expression.py
In the Mathics python code, there are a number of places where we need to strip off double quotes. This should have been a red flag that something was wrong in the design of Mathics. Around Mathics 2.2.0, we added a "string_quotes" parameter to `to_python()` so that we could specify the behavior. 
However, more recently in getting rid of `get_string_value()` and replacing it with `value`, I see that `.get_string_value()`/ `.value` is another way that could have been used to not add quotes around the string in many of the offending cases that this occurs.
Note that  still need `to_python()`  when there are things like lists (or other composite structures) of strings and you want to specify whether or not to include quotes. 
This PR, simplifies string quote removal which is most noticeable …
=> List to python+roundtrip quotes

mathics/core/definitions.py, mathics/core/element.py
This PR moves the loading of formatter functions at an early position in the `mathics.core.definitions` module. This fixes the issue mentioned in https://github.com/Mathics3/mathics-core/blob/2a716c9f332555032fc7aafc3855dcfc9b6a809f/mathics/core/element.py#L344
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/548"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> earlier load of formatters

mathics/builtin/binary/io.py, mathics/builtin/box/graphics3d.py, mathics/builtin/drawing/plot.py, mathics/builtin/files_io/filesystem.py, mathics/builtin/numbers/numbertheory.py, mathics/builtin/numbers/randomnumbers.py, mathics/core/convert/function.py, mathics/core/element.py, mathics/core/symbols.py
Following the line of attempts to clarify, document, and remove flaky practices from the code, I collected in this PR the part of #551 in which @rocky seems to agree.
* adding the prototype of `to_python` in `BaseElement`.
* adding type annotations to its parameters.
* removing the use of the parameter n_evaluation in ``expr.to_python(n_evaluation=evaluation)`` in favor of ``eval_N(expr, evaluation).to_python()``.
* in the modified functions, make changes to avoid the same variable to represent objects of different classes from one line to the next one.
* adding several comments.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/552"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Removing the n_evaluation parameter from the `to_python` method

mathics/builtin/atomic/numbers.py, mathics/doc/documentation/1-Manual.mdoc, test/builtin/atomic/test_numbers.py
* Shy away from using markup that doesn't render properly in Django. In partuclar, math mode
* Add Wiki and WMA links in Accuracy and Precision builtin functions, and
* more cross refrences
* Move unit tests in autodoc to unit test
* reversed quote -> RawBackquote which is the WMA term for the character
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/553"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Go over docs for Accuracy and Precision

mathics/builtin/box/layout.py, mathics/builtin/makeboxes.py
Some small things noticed in recent Boxing discussion
* Add example for $BoxForms
* Add user docs for StyleBox and ShowStringCharacters
* newer-style attributes in layout.py
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/557"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Improve Box-related documentation

mathics/builtin/makeboxes.py, test/builtin/test_makeboxes.py
This PR moves several doctests (mostly about broken behavior) associated to MakeBoxes to (xfailed) pytest tests.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/558"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> moving pending doctests in MakeBoxes to pytests

CHANGES.rst, mathics/builtin/numbers/randomnumbers.py, test/builtin/numbers/test_randomnumbers.py
Fixes #468
RandomSample with one list argument should return a random ordering of the items in the given list, not just one item from the list.
Before:
```Mathematica
In[1]:= SeedRandom[42]; RandomSample[Range[10]]
Out[1]= {9}
```
After:
```Mathematica
In[1]:= SeedRandom[42]; RandomSample[Range[10]]
Out[1]= {9, 2, 6, 1, 8, 3, 10, 5, 4, 7}
```
=> Fix RandomSample and add test cases

mathics/builtin/scipy_utils/integrators.py, test/builtin/numbers/test_calculus.py, test/builtin/numbers/test_nintegrate.py, test/helper.py
During some checks I did yesterday, I found a typo that made that the scipy integrators were not loaded even if the scipy library is available. This PR fixes it, and adds some tests to detect this kind of bug.
* Fixing a typo that prevented that scipy integrators were loaded.
* Improving test_nintegrators and test_calculus.
* Improving test/helper.py to show the evaluation messages in case they are not expected.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/560"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fixing a typo in scipy_utils/integrators.py. Improving checks.

test/builtin/test_makeboxes.py
This PR adds several tests to reinforce the compatibility of Mathics formatting routines with WMA. I hope this is going to be helpful to understand better how this works in WMA, and how it could work here.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/563"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> adding test to reveal the internals of MakeBoxes

admin-tools/make-op-tables.sh, mathics/builtin/atomic/strings.py, mathics/builtin/base.py, mathics/builtin/drawing/image.py, mathics/builtin/files_io/files.py, mathics/builtin/layout.py, mathics/builtin/makeboxes.py, mathics/builtin/numbers/calculus.py, mathics/builtin/string/operations.py, mathics/core/convert/op.py, mathics/core/formatter.py, mathics/core/symbols.py, test/format/test_format.py
This revises the work done in the `ascii-op-to-Unicode` branch. 
I had a hard time understanding the flow of what's going on, and this process was both painful and made me a bit annoyed. 
I was pleased though at @mmatera start to move the makeboxes into its own module, and we have a _little_ bit of segregating boxing routines, so that I suppose helps a little.
It is not that the code isn't sophisticated or complicated. It is just that it is not organized and changes haven't been coordinated. 
Let me describe a little of the history around this PR and the code I see, and reflect. The aim show of this reflection shows how the code has become of poorer quality, is in constant need of serious refactoring, and can get worse with uncoordinated bug fixes or feature improvements. Functionally the …
=> Infix formatting

CHANGES.rst, mathics/builtin/assignments/internals.py, mathics/builtin/inout.py, mathics/core/definitions.py
In WMA, `$PrintForms` is a (not very well documented) variable that stores the possible formats in which an expression can be printed. This PR implements it in Mathics.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/565"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Implementing $PrintForms

.github/workflows/consistency-checks.yml, .github/workflows/osx.yml, .github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, Makefile, admin-tools/make-op-tables.sh, mathics/builtin/atomic/strings.py, mathics/builtin/base.py, mathics/builtin/drawing/image.py, mathics/builtin/files_io/files.py, mathics/builtin/layout.py, mathics/builtin/makeboxes.py, mathics/builtin/numbers/calculus.py, mathics/builtin/string/operations.py, mathics/core/convert/op.py, mathics/core/formatter.py, mathics/core/symbols.py, mathics/doc/latex/Makefile, mathics/docpipeline.py, mathics/session.py, mathics/settings.py, setup.py, test/format/test_format.py, test/helper.py
./admin-tools/make-op-tables.sh builds the JSON tables.
Also, environment variable MATHICS_CHARACTER_ENCODING can be used to set SYSTEM_CHARACTER_ENCODING
Some adjustments to tests with DifferentialD were made so we use standard Unicode symbols not WMA unicode.
There was a bug in gstest from a prior commit in mathics-scanner where the "pre-scanner()" was replacing strings starting with "|".
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/567"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Use ASCII to Unicode tables for Infix operators

.github/workflows/consistency-checks.yml, .github/workflows/osx.yml, .github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
We needed to use a branch of mathics-scanner in workflows CI. That branch now is in master, so we can simplify things a little in workflows testing.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/571"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Go back to using master branch in scanner

CHANGES.rst, mathics/builtin/options.py
I have been looking at "Computer Science with Mathematica_ Theory and Practice for Science, Mathematics, and Engineering" by Maeder. It uses `SetOptions` so this adds that. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/591"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add rudimentary SetOptions

mathics/builtin/assignments/internals.py, mathics/builtin/base.py
@rocky, these are my suggestions for your PR.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/592"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> my suggestions

CHANGES.rst, SYMBOLS_MANIFEST.txt, mathics/autoload/forms/StandardForm.m, mathics/builtin/assignments/clear.py, mathics/builtin/assignments/internals.py, mathics/builtin/base.py, mathics/core/definitions.py
In this PR
* the assignment to `MakeBoxes` is rewritten following the pattern of the other special cases.
* The last step of cleaning up in the load of `Definitions` is fixed, to avoid get ride of the builtin definitions for symbols that are overloaded in  the `autoload` step.
* the builtin `Remove`  is added.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/595"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> More suggestions and fixes

mathics/builtin/attributes.py
@rocky, please before merging #607, add this patch, to a bug that came up trying to load FeynCalc
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/608"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> catch not known attributes in ClearAttributes and SetAttributes

Makefile, mathics/builtin/attributes.py, mathics/core/attributes.py
`mathics.builtin.attributes`:
* `def apply(` -> `def eval(`
* Add WMA links 
* Class names ordered alphabetically
* Hard breaks in docstring removed
* Some incorrect references to "leaves" changed to "attributes"
`mathics.core.attributes`:
* Add short comments above flag value
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/607"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Update 'attributes' for current standards

mathics/builtin/files_io/files.py, mathics/builtin/files_io/filesystem.py, mathics/core/streams.py
Another random bug came up trying to see the progress in loading packages. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/606"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> fix a bug that makes that URLSave always fails

test/builtin/atomic/test_symbols.py, test/builtin/test_attributes.py, test/builtin/test_patterns.py
Move tests into more specific tests for the module that the tests are in.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/612"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Put test_rules_patterns tests where they belong

mathics/builtin/base.py
This PR is a part of #590 that helps to clarify the behaviour of `Buitlin.contribute`.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/600"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> improving clarity in Builtin.contribute

CHANGES.rst, mathics/builtin/assignments/assignment.py, mathics/builtin/assignments/internals.py, mathics/builtin/assignments/upvalues.py, test/builtin/test_assignment.py
This PR adds some comments on the internal implementation of the assignment methods. Also, adds tests to show some behaviors that must be fixed in order to improve the compatibility with WMA.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/601"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Adding comments and tests for Assignment

mathics/builtin/assignments/assignment.py, mathics/builtin/assignments/clear.py, mathics/builtin/assignments/types.py, mathics/builtin/assignments/upvalues.py, mathics/builtin/atomic/symbols.py, mathics/builtin/attributes.py, mathics/builtin/scoping.py, mathics/core/assignment.py, mathics/core/list.py, test/builtin/test_assignment.py
Move core-like assignment interals out of builtins and into core. (We may want to split up core more in the future though)
Better sort long list of assignment methods alphabetically
Some small RsT tagging in a docstring
Remove nonexistent word "evaluable"
Add yet another type annotation to a signature
Make test assert failure messages unique
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/622"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Changes suggested in PR review

mathics/core/rules.py, mathics/doc/common_doc.py, test/consistency-and-style/test_duplicate_builtins.py
`rules.py __setstate__()`:
`mathics.builtin.builtins` was renamed to `mathics.builtin._builtins`
I guess on the assumption it was private.
It turns out it wasn't. And we were using the older (more correct) name "builtins" instead of "_builtins". Use "_builtins" to make this work. `__setstate__` apparently isn't used right now, but would be if  we used `deepcopy()`. Note that in #635, this variable is renamed `system_builtins_dict`.
rest:
Change imports of Builtin from `mathics.builtin` to  `mathics.builtin.base`. `mathics.builtin only accidentially imports `Builtin`.
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/636"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Two bugs found via another PR

mathics/builtin/arithfns/basic.py, mathics/builtin/arithmetic.py, mathics/builtin/comparison.py, mathics/builtin/lists.py, mathics/builtin/specialfns/elliptic.py, mathics/builtin/specialfns/gamma.py, mathics/builtin/statistics/orderstats.py, mathics/core/convert/expression.py, mathics/core/expression.py, mathics/core/symbols.py, mathics/eval/__init__.py, mathics/eval/numerify.py, test/test_evaluators.py
In this second round, the `numerify` method is converted in a non-member function, under  `mathics.eval.numerify`
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/632"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> moving method numerify to function in mathics.eval.numerify

SYMBOLS_MANIFEST.txt, mathics/builtin/atomic/strings.py, mathics/builtin/matrices/constrmatrix.py, mathics/builtin/vectors/math_ops.py, mathics/data/.gitignore, mathics/eval/math_ops.py, mathics/eval/strings.py
Move some eval functions to `mathics.core.eval` go over the changed modules for apply->eval, <dd> tags, and WMA links and shorten some lines with <url>s in them. 
<a href="https://gitpod.io/#https://github.com/Mathics3/mathics-core/pull/645"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
Hexidecimal -> Hexadecimals
isort imports of changed modules
=> Move more eval functions from mathics.builtin to mathics.eval

mathics/core/symbols.py
Also note *why* we need `Symbol.__hash__()`
A while back, but I forget where, the justification for why we using Strings in function instead of  Symbols in the code was because `is` or equality testing was slow.  This simple change addresses that. 
I forget where the benchmarking data was posted for previous comparisons. I'd be interested though in what the change (if any) is.
=> Compute Symbol.__hash__() once

mathics/builtin/__init__.py, mathics/builtin/layout.py, mathics/eval/makeboxes.py
This provides an alternative implementation, that avoids using WL pattern matching to handle the different cases in ```MakeBoxes[Infix[...],format]```
=> alternative implementation for MakeBoxes[Infix[...],format]

test/consistency-and-style/test_summary_text.py
Some deprecated functions were removed, and the tests for the existence of "<dl>" tags and the balancing test were split.
=> clean and improve test/consistency-and-style/test_summary_text.py

mathics/builtin/box/graphics.py, mathics/builtin/drawing/plot.py, mathics/builtin/graphics.py
I encountered this when building the docs and something along the lines of
```
ParametricPlot[{Sin[u], Cos[3 u]}, {u, 0, 2 Pi}]
```
which creates in `mathics-229.asy`: 
In creating an axis it uses:
```
draw(, rgb(0.2472, 0.24, 0.6)+linewidth(0.66667));
```
The empty list of points is mysteriously coming from the default TickStyle `{}`.
We are seeing this  Asymptote only
Also TicksStyle handling seems weird since we shouldn't try to create LineBox in the first place.
=> Handle degenerate LineBox when there are no points

setup.py
Testing shows that we need this to read sunflowers.jpg and possibly do ColorNegate of that.
=> Bump requirement on Pillow to 9.2.0

setup.py
mathics/settings.py imports and uses `pkg_resources`, which comes from setuptools. While this is normally installed, it might not be present in very minimal deployments, so it's good to list it explicitly.
=> Add setuptools to install requirements

CHANGES.rst, mathics/builtin/base.py, mathics/builtin/image/base.py, mathics/builtin/image/misc.py, mathics/builtin/image/morph.py, mathics/builtin/image/test.py, mathics/builtin/manipulate.py, mathics/core/expression.py, mathics/version.py, requirements-full.txt, setup.py, test/core/test_expression.py
Set requires in builtins; adjust `requirements-full.txt`.
`_SkimageRequires` and `_ImageTest` set only some requires and that wasn't working.
But more fundamentally we shouldn't use class inheritance for just setting a class variable.
Instead, set the class variable inside the class. This is more direct and clear.
Add additional PyPI packages that are used in Manipulate and Transliterate Set requires in builtins; adjust requirements-full.
=> Set requires in classes, rather than in Helper functions; adjust `requirements-full.txt`

mathics/builtin/lists.py, mathics/builtin/options.py
And go over docs and summary text for these. Add examples.
=> Place options 'All' and 'None' in correct section

mathics/builtin/numeric.py, mathics/builtin/options.py, mathics/builtin/vectors/math_ops.py, mathics/eval/math_ops.py, mathics/eval/nevaluator.py, test/test_evaluators.py
Go over mathics.eval putting eval functions that might go into an instruction interpreter in the form eval_[Mathics-builtin-name] when there is only one evaluation function and some variation of that when there is more than one.
Some docstrings and summaries have been revised.
=> mathics.eval eval_Capital fns

mathics/builtin/arithfns/basic.py, mathics/builtin/arithmetic.py, mathics/builtin/atomic/numbers.py, mathics/builtin/binary/io.py, mathics/builtin/specialfns/bessel.py, mathics/builtin/specialfns/gamma.py, mathics/core/convert/mpmath.py
`PrecisionReal` numbers use `sympy.Float` numbers as their internal representation. At the time, `sympy.Float` uses `mpmath.mpf` numbers as their internal representation. Even if `sympy.Float` and `mpmath.mpf` accepts as a parameter a floating point number as decimal precision (dps), internally the precision is stored as an integer number bits. 
In our current master, we have an inconsistent use of the precision attribute: when we create a  `PrecisionReal` number, precision is measured in bits, but in `from_mpmath`, precision is passed as binary.  Apart from requiring several unneeded conversions, each time we pass from binary to decimal and backward, we lost accuracy in the estimation of the error, which is a problem if we want a consistent implementation for `Accuracy` and  `Precision`. …
=> from_mpmath precision twaks

mathics/builtin/assignments/assignment.py, mathics/core/definitions.py, mathics/eval/pymathics.py
What is in mathics.eval is primarily for builtin LoadModule
mathics.core are for atoms, symbols, parsing, conversion - things at the very lowest level that aren't focused directly around evaluation of a particular Mathics3 builtin function.
=> mathics.core.pymathics -> mathics.eval.pymathics

mathics/builtin/assignments/assignment.py, mathics/builtin/scoping.py, mathics/doc/common_doc.py, mathics/doc/latex/doc2latex.py, mathics/doc/latex_doc.py, mathics/docpipeline.py
This allows Mathics3 Modules loaded via `-l` or `--load-module` on the `docpipetest.py` command like to get loaded 
using  `eval_LoadModule` the underlying eval method for `LoadModule[]`.
In other words, from Mathics3 core you can test Mathics3 Modules or select individual sections Mathics3 Module tests. But that also means, we are collecting XML-like  documentation and test data which can then be put into the LaTeX-generated PDF.
I believe the information will go into the PCL (Python Pickle file), but I haven't tested that yet.
And I  haven't looked at the piece that puts creates `documentation.tex`  (`mathics/doc/latex/doc2latex.py`)
I think that will be another (small) PR.  This is large enough as it is.
For expediency in being able to get this accomplished over the weekend in a …
=> Reinstate pymathics doc

mathics/builtin/files_io/files.py, mathics/builtin/string/operations.py, mathics/core/evaluation.py
This PR fixes an issue reported by @rocky, where the behavior or `Put` was modified when is was called from mathics-server.  Now, in `mathics.builtin` all the references to `format_output` which is modified by mathics-server  were rempaced by calls to `format_element` and `boxes_to_text`.
=> removing the use of Evaluation.format_output in builtins

mathics/builtin/arithfns/basic.py, mathics/builtin/arithmetic.py, mathics/builtin/specialfns/gamma.py, mathics/eval/arithmetic.py
This PR starts to move the context independent arithmetic to a separate module. Interestingly, just by moving around a little piece of code, the doctest time seems to be reduced in another 10 seconds in my machine, it is, a 13%.
=> move basic arithmetic to mathics.eval.arithmetic

mathics/doc/latex_doc.py
The same as in https://github.com/Mathics3/mathics-django/pull/190
This single line PR is a proposal about how to handle long urls in docstrings. With this patch
```
<url>:NetworkX:
https://networkx.org/documentation/networkx-2.8.8/reference/algorithms/\
generated/networkx.algorithms.tree.mst.minimum_spanning_edges.html
</url>
```
the <url></url> tag is processed as
```
<a href=https://networkx.org/documentation/networkx-2.8.8/reference/algorithms/generated/networkx.algorithms.tree.mst.minimum_spanning_edges.html>NetworkX</a>
```
=> removing blanks from url

Makefile, mathics/builtin/exp_structure/general.py, mathics/doc/latex/Makefile, mathics/doc/latex/mathics.tex, mathics/doc/latex/sed-hack.sh, mathics/docpipeline.py
I noticed this when looking into what it would take to get pymathics.graph graphs to format properly. 
<strike>I don't see a beneficial effect when doing this, but I imagine that</strike> as we get more proper formatting it <strike>may be</strike>  is an issue, so may as well fix it here now. 
(Short story there - all of this should be doable on the pymathics.graph side, but it will take writing some MakeBox rules, and adding a asymptote formatter for GraphBox on the pymathics.graph side. This is probably not something we should undertake before release.)
=> Format to LaTeX when we are writing to LaTeX

mathics/builtin/forms/output.py, mathics/builtin/numbers/constants.py, mathics/eval/makeboxes.py
This fix the issue mentioned in https://github.com/Mathics3/mathics-core/issues/784#issuecomment-1434767955:
With this PR, in the CLI,
```
In[1]:=Pi
Out[1]=Pi
In[2]:=OutputForm[Pi]
Out[2]=Pi
In[3]:=StandardForm[Pi]
Out[3]= π
```
=> fix do_format_element

mathics/doc/common_doc.py
@mmatera  - Does this fix the problem that ~ 2/3 of the doctests do not get loaded? 
For reference, 1c35f0feeeaab9e26da1c1dd9c69db2af6c565b9 is the SHA before this merge and f0e04d647 I think is the commit after that. 
If this works, just merge it in. Or feel free to adjust this. 
Sorry for the breakage.
=> Revert get_section_test() addition

CHANGES.rst, mathics/doc/documentation/1-Manual.mdoc
I'd like to do a revision of the roadmap `FUTURE.rst` but that will be in a separate PR. 
Some of this is not a neat as I would like, I think there is still a bit of duplication to remove. But I wanted definitely to remove the homegrown doctest stuff as a "feature" (in the positive sense).
=> Intro revision

FUTURE.rst, PAST.rst
I should have started this earlier and we should have started a longer discussion of this. 
But hey this is a start. I want to have something in place for the 6.0.0 release.
Your comments and ideas are welcome. 
I seem to recall something around `\!`  that involved precedence that was deferred that might go on the list.
=> Start noting what's up and what goals have been met

SYMBOLS_MANIFEST.txt, mathics/builtin/layout.py, mathics/builtin/makeboxes.py
This came up during the #766 rebase: `PrecisionForm` didn't have a `Builtin` symbol, and the `Makeboxes` rule didn't take into account the `form` parameter. This PR fixes these two issues.
=> fix MakeBoxes[PrecedenceForm[...],form]

CHANGES.rst, mathics/builtin/arithmetic.py, mathics/eval/arithmetic.py, test/builtin/arithmetic/test_basic.py
CHANGES.rst
-----------
this is a continuation of prior work, not an external API change
arithmetic.py
-------------
* eval_{abs,sign} -> eval_{Abs,Sign};
* remove MakeBoxes hack - will handle by a more pervasive go-over of Precedence.
* generic style things changes.
- Split long URL lines
- reduce use of  %(name)s
- order class definitions
test_basic.py
-------------
Isolate failing DirectedInfinity tests
=> Improve directed infinity

mathics/autoload/rules/Bessel.m, mathics/builtin/specialfns/bessel.py
This PR improves the rules for Bessel functions of half integer index.
=> improving rules for Bessel functions with half integer indices

CHANGES.rst, SYMBOLS_MANIFEST.txt, mathics/autoload/rules/Bessel.m, mathics/autoload/rules/Element.m, mathics/builtin/arithmetic.py, test/builtin/arithmetic/test_element.py, test/builtin/specialfns/test_bessel.py
This PR adds the built-in `Element`, which is used in defining certain integrals. In particular, it would be useful to extend more the support for integral representations of special functions.
Also, I noticed that when `Set`/`SetDelayed` expressions with a LHS involving named patterns appear in autoload files, the temporal names can spoil the `System` namespace, making some test fail. A way to prevent that is to enclose the code of the modules in a `Begin`/`End` statement. Public symbols defined in the module appear then before the private block, by assigning a usage string.
=> adding Elements. Local symbols in rules/Bessel.m  inside a private context.

mathics/builtin/arithmetic.py, mathics/builtin/atomic/atomic.py, mathics/builtin/atomic/numbers.py, mathics/builtin/atomic/strings.py, mathics/builtin/atomic/symbols.py, mathics/builtin/base.py, mathics/builtin/image/test.py, mathics/builtin/list/associations.py, mathics/builtin/list/constructing.py, mathics/builtin/options.py, mathics/builtin/quantities.py, mathics/builtin/string/characters.py, mathics/builtin/testing_expressions/expression_tests.py, mathics/builtin/testing_expressions/list_oriented.py, mathics/builtin/testing_expressions/numerical_properties.py, mathics/core/atoms.py, mathics/core/convert/python.py, mathics/core/list.py, mathics/core/symbols.py, mathics/eval/numbers.py
Supersedes #820. 
As is common, the changes needed are far too great to do in one programming session. So this is the first part.
=> Reduce RealNumberQ and refactor

mathics/autoload/rules/Element.m
This PR just fixes a couple of typos in the `Element.m` autoload module
=> System`Element typos

mathics/builtin/arithmetic.py, mathics/builtin/atomic/strings.py, mathics/builtin/binary/io.py, mathics/builtin/functional/functional_iteration.py, mathics/builtin/list/rearrange.py, mathics/builtin/numbers/algebra.py, mathics/builtin/string/operations.py, mathics/builtin/testing_expressions/equality_inequality.py, mathics/core/atoms.py, mathics/core/convert/mpmath.py, mathics/core/expression_constants.py, mathics/core/expression_predefined.py, mathics/eval/parts.py
This comes from #828. Here a new module is added to contain the expression constants of the form `DirectedInfinity[...]`.
=> Expression constants

mathics/autoload/rules/Limit.m, mathics/builtin/numbers/calculus.py, test/builtin/arithmetic/__init__.py, test/builtin/calculus/__init__.py, test/builtin/calculus/test_limit.py, test/builtin/calculus/test_solve.py
These were culled from symja_android_library/rules/LimitRules.m. More to come. 
I have noticed that as we add add more autoloaded rules, initial loading slows down. At some point I hope to rectify this by some sort of image loading mechanism that Lisps and Smalltalk have.
But also, we need to speed up readling loading overall.
=> Start adding Limit[] rules

mathics/core/expression.py, mathics/core/list.py, test/builtin/box/test_custom_boxexpression.py
In the `BaseElement` hierarchy, as any other Python object, the elements have two different internal methods: `__str__` and `__repr__`. The general aim of these methods is explained here:
https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr
In Mathics, we have different ways to store the same expression. For example, we want to distinguish between 
`ListExpression(Integer0, Integer1)` and `Expression(SymbolList, Integer0, Integer1)`. `__repr__` does this by sorrounding each element of the expression with "<type: ....>".
On the other hand, `__str__` returns something that should be evaluable, because it is used to convert any of these objects into a string representation.
However, in the current master, there is an inconsistency that originates the issue …
=> fix inconsistency in ListExpression.__str__ and Expression.__repr__

mathics/builtin/__init__.py, mathics/builtin/atomic/strings.py, mathics/builtin/atomic/symbols.py, mathics/builtin/files_io/filesystem.py, mathics/builtin/string/operations.py, mathics/builtin/string/patterns.py, mathics/builtin/vectors/math_ops.py, mathics/core/convert/regex.py, mathics/eval/math_ops.py, test/core/convert/test_to_regex.py
This implements the idea of passing a `Callable` object instead of an `Evaluation` object when the object is just used to show a message. 
Also, a default `Callable` was introduced which does the same than `Evaluation.message` when an evaluation object is not available.
=> Evaluation message to callable

mathics/builtin/compilation.py, mathics/core/element.py, mathics/core/expression.py, mathics/core/symbols.py, mathics/eval/arithmetic.py
The motivation for this was originally just to note as a TODO that `get_rules_list()` should be eventually moved inside the `ListExpression` class. 
In doing that though LSP was showing a number of errors, some have been corrected. 
And then in breaking up some (but not all) of the long comment lines, I had a hard time understanding some of the  comments. I have tried to rephrase, but @mmatera please make sure I haven't mangled the meaning in the process.
The comment at the end of `rewrite_apply_eval_step`  I don't quite understand.
=> Another look over expression.py

test/builtin/drawing/test_image.py, test/builtin/numbers/test_calculus.py
=> pytest succeeds without scikit-image

mathics/builtin/__init__.py, mathics/builtin/atomic/symbols.py, mathics/builtin/scoping.py, mathics/core/load_builtin.py, mathics/doc/common_doc.py, mathics/docpipeline.py, mathics/eval/pymathics.py, mathics/format/mathml.py, test/consistency-and-style/test_duplicate_builtins.py, test/consistency-and-style/test_summary_text.py
Next iteration in sequence of refactorings. 
Here, the remaining code that should have been put into a function has been moved out of `mathics/builtin/__init__.py` and into `mathics.core.builtin_load` and imports have been adjusted which reduces circular dependencies. 
Remaining refactoring: 
Initiate the module loading from  the `mathics.core.builtin_load` module. 
Loading currently needs to be rewritten. It currently gets _all_ builtin module names. then from that returned collection imports _all_ module names, then from that collection ... _all_ ... _all_ ...
Instead,  of many "all" loops, we need to do follow through everything a specific module name.  To do everything, that is in one loop (over builtin module names) and no further loops would follow.
=> Move more builtin module loading code out of `mathics/builtin/__init__.py`

mathics/builtin/drawing/drawing_options.py, mathics/builtin/drawing/graphics3d.py, mathics/builtin/drawing/plot.py, mathics/builtin/options.py, mathics/doc/latex/Makefile, mathics/doc/latex/sed-hack.sh
Move graphics-drawing options under drawing. (The creation of this predated when we had guide sections. This not only makes more sense, but currently we can't reference chapters in LaTeX
Makefile: build we build documentation in include the non-test/tutorial Pymathics modules.
sed-hack.sh work around doctest bug that strips the "s" in a Section name.
=> Yet another round of documentation-inspired fixes

admin-tools/build_and_check_manifest.py, examples/symbolic_logic/gries_schneider/test_gs.py, mathics/builtin/__init__.py, mathics/core/definitions.py, mathics/core/load_builtin.py, mathics/doc/common_doc.py, mathics/doc/latex_doc.py, mathics/docpipeline.py, mathics/main.py, mathics/version.py, test/consistency-and-style/test_duplicate_builtins.py, test/helper.py
... YAY!
This paves the way for further improvements.
=> Move builtin loading code entirely out of __init__

mathics/builtin/arithfns/basic.py, mathics/builtin/arithmetic.py, mathics/builtin/numbers/calculus.py, mathics/builtin/numbers/constants.py, mathics/core/convert/mpmath.py, mathics/format/latex.py, test/builtin/arithmetic/test_basic.py, test/builtin/atomic/test_numbers.py, test/builtin/numbers/test_calculus.py, test/builtin/numbers/test_constants.py, test/builtin/test_assignment.py, test/builtin/test_comparison.py, test/builtin/test_patterns.py, test/core/parser/test_convert.py, test/format/test_format.py
In this PR, I start to move some private doctests to Pytest. I also propose some extra related tests and check that the expected behavior matches with obtained in WMA.
From this, it came up that we are handling wrong how ```  0. I``` is evaluated: In master, it is evaluated to `0.`, but in WMA, it is evaluated to ```  Complex[0.`, 0.`] ```.
To match this behavior, I had to modify `from_mpmath`, and deactivate its lru_cache.  The problem now with lru_cache is that  `mpmath.mpf(0.)` produces the same hash than `mpmath.mpc(0., 0.)`, which looks wrong.
=> Moving private doctests to pytests. Fix the compatibility issue 0. I-> 0.

mathics/core/convert/mpmath.py
I did this before, but for some reason it wasn´t merged...
=> Restoring lru

CHANGES.rst, mathics/builtin/arithmetic.py, mathics/builtin/image/misc.py, mathics/builtin/image/morph.py, mathics/builtin/image/pixel.py, mathics/builtin/manipulate.py, mathics/builtin/matrices/constrmatrix.py, mathics/builtin/numbers/calculus.py, mathics/builtin/numbers/trig.py, mathics/builtin/numeric.py, mathics/builtin/patterns.py
Rename this symbol for compatibility with the last version of WMA
=> RealNumberQ->RealValuedNumberQ

mathics/core/load_builtin.py, mathics/data/.gitignore, mathics/doc/latex/.gitignore
Second pass at making it possible to load a single module inside `mathics.builti`  rather than all modules at once.
* the loop updating ``display_operators_set`` is now done inside module import rather than its own independent loop.    
*  `add_builtins_from_builtin_module()` isolated from inside `add_builtins_from_builtin_modules()` so that we can eventually remove  the latter.
*  More type annotations, docstrings and comments.
=> A second pass at redoing load_builtin.py

.github/workflows/osx.yml, mathics/builtin/image/basic.py
Unversioned llvm brew install is needed now. (Before,  it _had_ to be versioned). 
Allow more flexibility in the `Threshold[]` result value. 
it was a hassle to get this working again on OSX.
=> Does tesseract-lang now need to be installed?

mathics/builtin/evaluation.py, mathics/builtin/procedural.py, mathics/builtin/system.py, test/builtin/test_evalution.py, test/builtin/test_forms.py, test/builtin/test_procedural.py, test/builtin/test_strings.py, test/builtin/test_system.py, test/core/parser/test_parser.py, test/helper.py
=> move private doctest to pytest for evaluation, procedural and system

mathics/builtin/messages.py, mathics/builtin/options.py, mathics/builtin/scoping.py, test/builtin/test_messages.py, test/builtin/test_options.py, test/builtin/test_scoping.py, test/core/parser/test_parser.py
Another bunch of private doctests converted in pytests. Maybe the most drastic change here regarding the tests is that with these changes, the content of the syntax error messages is not tested anymore.
=> Move private doctests to pytest11

mathics/builtin/directories/directory_names.py, mathics/builtin/file_operations/file_properties.py, mathics/builtin/file_operations/file_utilities.py, test/builtin/test_directories.py, test/builtin/test_evalution.py, test/builtin/test_file_operations.py
=> Move private doctests to pytest16

mathics/builtin/tensors.py
This PR adds the missing ConjugateTranspose[] function.
=> Add conjugate transpose function

mathics/builtin/testing_expressions/list_oriented.py, mathics/eval/testing_expressions.py
At present ``ArrayQ`` returns ``False`` for ``SparseArray`` (which is inconsistent with Mathematica). This (draft) PR will fix this problem. 
It's also a preparation for ``TensorProduct`` that I plan to bring in in a few weeks, which will make rules of ``TensorProduct`` clearer.
For me there are two things of concern about this (draft) PR:
1. ``ArrayQ`` (``MatrixQ``) has been used throught out Mathics3. Though all tests have been passed, numerous problems may occur (e.g. ``Transpose[a_SparseArray]``, which returns the same expression as input now, but will cause an ``AttributeError`` in this PR). In a way this reminds us that there's still quite a bit to be done about ``SparseArrays``.
2. Rules like ``"ArrayQ[expr_]": "ArrayQ[expr, _, True&]"`` don't look efficient, all the evaluation on …
=> Fix ArrayQ for SparseArray

mathics/builtin/list/constructing.py
Now ``Range`` is still not applicable to general ``di`` like ``Pi``. I'm not sure if it's worth sacrificing efficiency to make ``Range`` work for general real-valued ``di`` as ``IterationFunction`` does.
=> Fix ``Range`` for negative ``di``

mathics/builtin/procedural.py
Just adding the explanation about how parameters in `Switch` are handled in the documentation.
=> Improve switch doc

CHANGES.rst, mathics/builtin/box/graphics.py, mathics/builtin/box/graphics3d.py, mathics/builtin/drawing/graphics3d.py, mathics/builtin/graphics.py, mathics/format/latex.py, mathics/format/svg.py, test/builtin/drawing/test_plot.py
Here we go with a proposal to address #964. The idea is that when an invalid graphics primitive is processed, a pink rectangle is drawn instead. Notice that in WMA no error message is shown in the client. Just the pink background is shown in the image, plus a tooltip in the notebook interface.
=> handle box errors in graphics and graphics3d

mathics/builtin/box/expression.py, mathics/builtin/box/graphics.py, mathics/builtin/box/graphics3d.py, mathics/builtin/colors/color_directives.py, mathics/builtin/drawing/drawing_options.py, mathics/format/latex.py, mathics/format/svg.py, test/format/test_asy.py, test/format/test_format.py, test/format/test_svg.py
This PR adds the entry for `Background` in the documentation and provides support for opacity in SVG and json graphics.
=> background documentation and opacity support

mathics/packages/DiscreteMath/CombinatoricaV0.9.m
This fixes the issue with `Elements` in loading Combinatorica, reported in #971.
=> fix CombinatoricaV0.9 for issue #971

mathics/builtin/attributes.py, mathics/builtin/messages.py, mathics/builtin/numbers/calculus.py, test/builtin/numbers/test_calculus.py
This PR prevents ``True'``, ``False'`` and ``List'`` be evaluated producing the error reported in #971. Comments explaining how the rule for evaluating `Derivative` over anonymous functions works was added.
=> Fix Derivative issue discussed in #971

mathics/doc/common_doc.py, mathics/doc/latex_doc.py, mathics/docpipeline.py, test/doc/test_common.py
This PR is mainly about clarifying the code in the documentation system
* sort classes and functions in mathics.doc.common according to the order in doc-code-revision (and as in #981)
* adding docstrings
* changing some names of classes and functions to be more explicit about their role in the system
* adding Pytests for the documentation system.
* fix a typo (section ->section_all) in mathics.doc.latex_doc  to allow load the GuideSections in the LaTeX documentation.
* fix an indentation error in the former ``gather_tests`` function previously reported in #981.
=> Go over the documentation of the documentation system

test/builtin/test_directories.py
Discovered because this test produced a stack overflow in the windows test action in #987
=> adjust the docstring in directory private doctests

mathics/doc/common_doc.py, mathics/docpipeline.py
This PR continues #990 by moving the inner loop that loads chapters in `MathicsMainDocumentation.doc_part` to a new method `MathicsMainDocumentation.doc_chapter`. With this change, the "on the fly" loading of documentation for Pymathics modules loaded in a Django session now is possible (and is implemented in https://github.com/Mathics3/mathics-django/pull/201)
=> Doc code another round of tiny changes 2

mathics/builtin/files_io/files.py, mathics/core/definitions.py, mathics/eval/files_io/files.py, mathics/main.py
Currently the global variables `$Input` and `$InputFileName` are not set correctly. This pull request fixes this.
- Create a file `script.m` with contents  
```
Print["Input: ",$Input]
Print["InputFileName: ", $InputFileName]
```
- Within mathics execute: `Get["script.m"]`
- or call the script from the command line `mathics script.m`
Using `Get` the global variables are not set at all.
```
In[1]:= Get["script.m"]
Script Input: 
Script InputFileName: 
Out[1]= None
```
From the command line `InputFileName` is set, but not the full path. `Input` is still unset.
```
Script Input: 
Script InputFileName: script.m
```
```
In[1]:= Get["script.m"]                                                        
Input: script.m
InputFileName: /full/path/to/script.m
```
=> Handle setting $Input and $InputFileName during Get[]

mathics/builtin/colors/color_operations.py, mathics/builtin/drawing/plot.py, mathics/builtin/fileformats/htmlformat.py, mathics/builtin/fileformats/xmlformat.py, mathics/builtin/files_io/importexport.py, mathics/builtin/inference.py, mathics/builtin/numbers/algebra.py, mathics/builtin/numbers/diffeqns.py, mathics/builtin/patterns.py, mathics/builtin/pympler/asizeof.py, mathics/core/convert/expression.py, mathics/core/pattern.py, mathics/core/rules.py, mathics/core/subexpression.py, mathics/eval/numbers/calculus/series.py, test/core/test_expression_constructor.py, test/core/test_sympy_python_convert.py
In some versions, black seems to want optional "," at the end of the last parameter.
In support of getting #1013 to build cleanly
=> black weirdness wars

mathics/doc/common_doc.py, mathics/docpipeline.py
After the last changes in the documentation system, `requires` was not taken into account in docpipeline. This PR fixes that.
=> Fix required test in doctests

pyproject.toml, setup.py
This makes it possible to install mathics directly from the repo, using `pip install git+https://github.com/Mathics3/mathics-core`
Also updating the definition of the Python packages in `pyproject.toml`.
=> `setup.py`: Build `op-tables.json` as part of "build_py"

mathics/builtin/attributes.py, mathics/builtin/box/__init__.py, mathics/builtin/files_io/importexport.py, mathics/builtin/vectors/__init__.py
This PR fixes some possible misunderstood escaped characters, which now produce a warning.
=> Fixing single \Mathics in docstrings

mathics/builtin/arithmetic.py, mathics/builtin/numbers/numbertheory.py, mathics/core/atoms.py, pyproject.toml
And here we have a partial compatibility patch. The root of the issues seems to be the change in which comparisons between `sympy.Float` and `float` are done from sympy 1.13.
It breaks several things, including the cache mechanism for complex numbers. This draft makes it works by disabling the cache.
=> sympy  1.13 compatibility

pyproject.toml
MathicsScanner currently supports 3.8 or greater in order to support Sympy 1.11. And MathicsScanner is a prerequiste of this package.
=> Minimum Python version supported is 3.8

mathics/builtin/forms/output.py, mathics/builtin/makeboxes.py, mathics/core/atoms.py, test/builtin/test_makeboxes.py, test/builtin/test_number_form.py
pyproject.toml: we don't support sympy 1.13.1 just yet
makeboxes.py: Add annotations, docstrings and remove ambiguity
test_number_for.py: test changed routines
output.py: More NumberForm docstring examples
=> Go over number format boxing

mathics/builtin/arithfns/basic.py, mathics/builtin/arithmetic.py, mathics/builtin/assignments/assignment.py, mathics/builtin/assignments/clear.py, mathics/builtin/atomic/strings.py, mathics/builtin/binary/system.py, mathics/builtin/binary/types.py, mathics/builtin/datentime.py, mathics/builtin/directories/system_directories.py, mathics/builtin/drawing/drawing_options.py, mathics/builtin/drawing/plot.py, mathics/builtin/evaluation.py, mathics/builtin/fileformats/htmlformat.py, mathics/builtin/fileformats/xmlformat.py, mathics/builtin/files_io/files.py, mathics/builtin/functional/composition.py, mathics/builtin/graphics.py, mathics/builtin/kernel_sessions.py, mathics/builtin/list/associations.py, mathics/builtin/mainloop.py, mathics/builtin/numbers/algebra.py, mathics/builtin/numbers/constants.py, mathics/builtin/numbers/randomnumbers.py, mathics/builtin/numeric.py, mathics/builtin/patterns.py, mathics/builtin/procedural.py, mathics/builtin/specialfns/gamma.py, mathics/builtin/system.py, mathics/builtin/testing_expressions/logic.py, mathics/builtin/testing_expressions/numerical_properties.py
This PR just normalizes the line breaks after </dl> in the docstrings
=> normalizing linebreaks after </dl>

mathics/doc/latex/mathics.tex
This PR adjusts the margins inside the Definition block in the PDF documentation. As a result this:
looks now like this:
=> adding margins inside the definition block in latex documentation

mathics/builtin/atomic/numbers.py, mathics/doc/documentation/1-Manual.mdoc, mathics/doc/latex/mathics.tex
Change PDF doc title to Mathics3 (Can be revised later to something nicer looking)
More grammar and doc corrections
Squelch some some lint messages in numbers.py
=> Small doc changes

.gitignore, CHANGES.rst, ChangeLog-spell-corrected.diff, Makefile, mathics/version.py
Go over release notes. Add a way to correct spelling mistakes in ChangeLog produced (which is used to create CHANGES.rst)
=> Get ready for release 7.0.0

mathics/docpipeline.py, test/builtin/files_io/test_importexport.py
Fix some doctest and pytest bugs...
test.parameters.{doc_even_if_error,keep_going}:
*  `doc_even_if_error` is not defined; `keep_going is`.
mathics/docpipeline.py:
*  remove find_texdata_folder(): it is not used and it also refers to a nonexistent class element
*   `test_case(... fail: Optional[]...= ...)` allows an explicit None to be passed. `None` was not tested for in using ` fail()`. Make parameter not optional
* call to doctest_pripile.print_and_log missing f-string specifier.  Not sure why we need the for loop.
* start_time needs to be initialized
test/builtin/files_io/test_importexport.py:
* test was pollutes local file system with `123.txt`. Ideally *None* of the tests would work in the local filesystem; a _temporary_ file system is okay though.
=> Misc doctest and pytrest fixes

pyproject.toml
This should fix #932. For some reason, CI does not see any difference, but it doesn't hurt to add it.
=> adding packaging as an explicit dependency (#932)

test/builtin/files_io/test_files.py
Ideally, we should be setting $InitialDirectory to $TempoarayDirectory as well. We should not be writing into $InitialDirectory which is not guaranteed to be writable.
=> Fix one more test that pollutes the filesystem

pyproject.toml, test/builtin/files_io/test_files.py, test/helper.py
As General Peron said, "Better than saying is doing". This is what I was talking about in #1067.
Also, I improved some docstrings a little bit.
=> Using tmp as pwd in pytests

mathics/doc/latex/Makefile, mathics/doc/latex/mathics.tex
Looking at the grey margin space around definition lists, it is still a little too large. 0.6em matches the vspace.
Somewhere I read a design principle that one should try reduce the overall number of different kinds of spacing.
=> Change dl margin space to match vspace length

mathics/builtin/numbers/calculus.py, mathics/builtin/numbers/exp.py, mathics/builtin/specialfns/gamma.py, mathics/core/builtin.py, mathics/core/convert/sympy.py
Generally, we can get sympy_name from the object.
Previously, we sometimes we had two-parameter "from_sympy()" calls and three-parameter calls where sometiems a parameter might not be used.
Overall, I think this will simplifies things.
Some type annotations were added.
=> Remove "sympy_name" in from_sympy() calls:

CHANGES.rst, mathics/builtin/numbers/algebra.py, mathics/builtin/numbers/numbertheory.py, mathics/core/convert/sympy.py, mathics/core/symbols.py, test/core/test_sympy_python_convert.py
This PR just fixes the pytest, and marks some issues in the conversion of Lambda functions.
=> fix tests for sympy conversions

.github/workflows/osx.yml, .github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, Makefile, admin-tools/make-op-tables.sh, admin-tools/make-operator-tables.sh, mathics/core/builtin.py, mathics/core/symbols.py, mathics/data/.gitignore, setup.py, test/core/test_sympy_python_convert.py
Prefer operator precedence from mathics-scanner tables.
=> Table driven operator precedence

.github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, mathics/core/element.py, mathics/core/expression.py
@mmatera looked the code over and do not find anything wrong with it. 
I made some small changes to the docstring comment and addressed some of the lint errors my editor is telling me about.
We can't use generators here since there we access and then "rewind" sometimes. And this _is_ essentially a version without the tail recursions.  So I've removed the comments concerning doubt.
If you have the example that caused the failure on 3.12 without this change, it would be interesting to benchmark just this test inside a Mathics3 session to see if there's any difference in execution time. 
Other comments I'll put in the specific code changes in this PR.
=> SameQ[]  and Expression module tweaks

CHANGES.rst, mathics/builtin/patterns.py, mathics/core/builtin.py
Looking at the initialization process, `Blank*` PatternObjets are created several times. This PR makes that these elements be created just once when a parameter is not provided. This would also help to optimize the pattern-matching algorithm when we face that problem.
=> Blanks as singleton

mathics/builtin/trace.py, mathics/core/builtin.py, mathics/core/rules.py, mathics/main.py
The name Builtin is vague, since there are things that are "builtin" (like variables and symbols) that are not functions.
Furthermore, BuiltinRule handles functions added by Mathics3 modules.
=> BuiltinRule -> FunctionApplyRule

mathics/builtin/exp_structure/general.py, mathics/builtin/list/constructing.py, mathics/builtin/numbers/algebra.py, mathics/builtin/numbers/calculus.py, mathics/builtin/patterns.py, mathics/core/builtin.py, mathics/core/pattern.py, mathics/core/rules.py, mathics/eval/numbers/calculus/series.py, mathics/eval/patterns.py, mathics/eval/testing_expressions.py
Here are some minor things noticed in looking over this module.
There is something that greatly bothers me that isn't fixed though. 
In this module, the base class is named `Pattern`. Elsewhere, base classes are prefaced with `Base`. For example, `BaseElement`,  `BaseRule`, or `BaseForm`.  
And then, because of this, the builtin function `Pattern[]` in module `mathics.builtin.pattern` uses the class name `Pattern_`.
To me, all of this feels like a gratuitous complication (even though I imagine this was due to sloppiness).
=> Minor things noticed in looking over the code

mathics/builtin/exp_structure/general.py, mathics/builtin/list/constructing.py, mathics/builtin/numbers/algebra.py, mathics/builtin/numbers/calculus.py, mathics/builtin/patterns.py, mathics/core/builtin.py, mathics/core/pattern.py, mathics/core/rules.py, mathics/eval/numbers/calculus/series.py, mathics/eval/patterns.py, mathics/eval/testing_expressions.py
In line with the last changes proposed by @rocky, I was doing a pass over mathics.core.pattern and fixing some issues reported by the linter.
=> Starting to tidy up mathics.core.pattern

mathics/core/pattern.py
Replace `pat.get_head_name() == "System`Pattern"` with  `isinstance(pat, Pattern)`.
I think there are other places where we are using ``get_head_name() == "System`xxx`` but that is left for a different time.
=> Simplfy checking for patterns

mathics/builtin/atomic/symbols.py, mathics/builtin/drawing/plot.py, mathics/eval/drawing/plot.py
* Add `ListStepPlot[]` 
* Refactor `_ListPlot[]` a little; note this is an abstract class. Add a ListPlot type enum
* mathics.eval.plot -> mathics.eval.drawing.plot
=> Add ListStepPlot refactor _ListPlot a little

mathics/builtin/compilation.py, mathics/compile/__init__.py, mathics/compile/types.py, mathics/core/convert/function.py, mathics/eval/distance.py, mathics/eval/drawing/plot.py, mathics/eval/files_io/read.py, mathics/eval/hyperbolic.py, mathics/eval/strings.py, pyproject.toml, requirements-full.txt, test/builtin/atomic/test_strings2.py, test/builtin/test_compilation.py, test/builtin/test_compile.py, test/consistency-and-style/test_duplicate_builtins.py, test/doc/test_common.py, test/doc/test_doctests.py, test/doc/test_latex.py
Following the requirement in #1099, this PR makes the dependency in llvm-lite optional.
Notice that the "Action Tests" here still run over the full installation, which includes this library.
=> making llvmlite to be optional

mathics/builtin/exp_structure/general.py, mathics/builtin/list/constructing.py, mathics/builtin/list/eol.py, mathics/builtin/numbers/calculus.py, mathics/builtin/options.py, mathics/builtin/patterns.py, mathics/core/builtin.py, mathics/core/pattern.py, mathics/core/rules.py, mathics/eval/numbers/calculus/series.py, mathics/eval/parts.py, mathics/eval/patterns.py, mathics/eval/testing_expressions.py
When a ExpressionPattern is created, the way in which the matching with expressions is determined in part by the attributes of its head. For example, if `S` is `Orderless`, the match method of the pattern
`S[a_, v__Integer]` should check for different orders of the arguments.
Also, the match against patterns like `DirectedInfinity[1]` can be determined using the faster `sameQ` method, instead of using all the machinery for looking for named patterns inside.
This PR introduces some modifications in the way Pattern objects are created, to have earlier access to the attributes, and to determine if the pattern is a "Literal"
=> Earlier initialization of patterns

mathics/main.py
Adds post-mortem debugging on a fatal exception via trepan3k. There may be a way to also support pdb, but I didn't see done as easily.
=> Add post-mortem debugging via trepan3k

mathics/core/definitions.py
=> Additional changes to: bark if builtin rule cannot be stored.

mathics/builtin/atomic/strings.py, mathics/builtin/messages.py, mathics/builtin/string/charcodes.py, mathics/builtin/string/operations.py, mathics/builtin/string/patterns.py, mathics/eval/strings.py
Something I noticed during debugging something else. In looking at tracebacks, names in context are a bit more visible, making it easier when names reflect what's going on.
Also, an error message added to General and duplication in classes removed.
=> Noticed another ` _apply` that should be `eval_xxx`

mathics/builtin/intfns/combinatorial.py
I pulled out just the combinatorial functions from #1133, knocks a couple of items off the list in #500
=> Add missing builtins: combinatorial functions

.github/workflows/pyodide.yml, .gitignore, mathics/builtin/file_operations/file_properties.py, mathics/builtin/files_io/files.py, test/builtin/files_io/test_files.py, test/builtin/test_datentime.py, test/test_main.py, test/test_returncode.py
I figured it was worth testing the Pyodide support (#1099) a bit more comprehensively. The changes to the tests are just to skip the handful of cases that Pyodide doesn't support related to I/O and threading.
=> Add CI job for Pyodide

mathics/builtin/atomic/numbers.py, mathics/builtin/box/expression.py, mathics/builtin/list/constructing.py, mathics/builtin/list/rearrange.py, mathics/builtin/numbers/algebra.py, mathics/builtin/numbers/calculus.py, mathics/builtin/numbers/constants.py, mathics/builtin/numbers/numbertheory.py, mathics/builtin/numeric.py, mathics/builtin/scipy_utils/optimizers.py, mathics/builtin/statistics/orderstats.py, mathics/core/assignment.py, mathics/core/atoms.py, mathics/core/builtin.py, mathics/core/convert/expression.py, mathics/core/definitions.py, mathics/core/element.py, mathics/core/evaluation.py, mathics/core/expression.py, mathics/core/expression_predefined.py, mathics/core/list.py, mathics/core/pattern.py, mathics/core/rules.py, mathics/core/symbols.py, mathics/eval/makeboxes.py, mathics/eval/numbers/calculus/series.py, mathics/eval/pymathics.py, mathics/eval/rules.py, mathics/main.py
I've been going through fixing mypy errors, and have gotten through about half of them. In the process I've added some extra error handling that fixes some exceptions I've seen due to methods being called on the wrong types.
Current master:
> Found 1718 errors in 183 files (checked 443 source files)
This branch:
> Found 872 errors in 155 files (checked 443 source files)
Feel free to squash all these commits, the only reason I've left them separate is that I made sure the test suite was passing after each one.
=> Fix mypy errors

mathics/core/assignment.py, mathics/core/atoms.py, mathics/core/builtin.py, mathics/core/convert/expression.py, mathics/core/convert/function.py, mathics/core/convert/mpmath.py, mathics/core/convert/op.py, mathics/core/convert/regex.py, mathics/core/convert/sympy.py, mathics/core/definitions.py, mathics/core/element.py, mathics/core/evaluation.py, mathics/core/formatter.py, mathics/core/list.py, mathics/core/load_builtin.py, mathics/core/number.py, mathics/core/parser/convert.py, mathics/core/parser/parser.py, mathics/core/pattern.py, mathics/core/rules.py, mathics/core/streams.py, mathics/core/subexpression.py, mathics/core/symbols.py, mathics/core/util.py
This fixes the remaining mypy errors in `mathics.core`, with the exception of `mathics.core.expression` which needs a bit more work.
=> Fix remaining mypy errors in mathics.core

.github/workflows/mypy.yml, mathics/__init__.py, mathics/builtin/box/graphics.py, mathics/builtin/quantum_mechanics/angular.py, mathics/core/atoms.py, mathics/core/builtin.py, mathics/core/convert/mpmath.py, mathics/core/element.py, mathics/core/evaluation.py, mathics/core/expression.py, mathics/core/number.py, mathics/doc/doc_entries.py, mathics/doc/latex/doc2latex.py, mathics/doc/latex_doc.py, mathics/doc/structure.py, mathics/docpipeline.py, mathics/format/asy.py, mathics/format/asy_fns.py, mathics/format/mathml.py, mathics/settings.py, pyproject.toml, setup.py, test/consistency-and-style/test_summary_text.py, test/doc/test_latex.py, test/format/test_format.py
I've fixed up the remaining mypy errors outside of:
- `mathics.builtin` and `mathics.eval`: these still have quite a few errors, but are going to be a bigger job to go through than the core modules, and are probably easier to just knock off one by one incrementally
- `test/` which I'd say are lower priority for type checking
- `mathics/benchmark.py`: is this still used? It just crashes when I try to run it
For now I've just set the mypy config to ignore these directories so we can run a CI job to ensure that the other core modules continue to typecheck, but might be better to be a bit more selective.
There were also a couple bits of code I've commented out as they appeared to be dead as best I could tell, but tell me if I'm mistaken.
=> Add CI job for mypy

mathics/builtin/atomic/symbols.py, mathics/builtin/layout.py, mathics/builtin/numbers/diffeqns.py, mathics/builtin/patterns/rules.py, mathics/builtin/recurrence.py, mathics/core/builtin.py, mathics/eval/makeboxes.py, test/builtin/numbers/test_diffeqns.py
This PR includes some fixes and improvings for handling operator precedence. In particular, as in WMA, avoids wrapping in parenthesis the second element of `Rule[pat_, Function[...]]`.
=> Improving precedence comparison.

test/builtin/numbers/test_linalg.py
Tests for issue #1156
```python
(mathics) ~/git/mathics-core/test/builtin/numbers$ python -m pytest test_linalg.py
=================================================== test session starts ====================================================
platform linux -- Python 3.11.10, pytest-8.3.3, pluggy-1.5.0
rootdir: ~/git/mathics/mathics-core
configfile: pyproject.toml
plugins: anyio-4.6.2.post1, typeguard-4.3.0
collected 32 items
test_linalg.py ................................                                                                      [100%]
===================================================== warnings summary =====================================================
../../../mathics/settings.py:13
~/git/mathics/mathics-core/mathics/settings.py:13: DeprecationWarning: pkg_resources is …
```
=> Update tests for issue #1156

mathics/core/symbols.py, test/core/test_symbols.py
And start a unit test for mathics.core.symbols. 
(Much more testing of that class would be nice, but that's left for some other time.)
=> Respect "short" option in Symbol.get_name()

mathics/builtin/no_meaning.py, mathics/core/builtin.py
@mmatera Please look this over when you have a chance to see if this "no-meaning"  Star operator is done properly.
@axkr says that it would be needed for Rubi.
=> Start Operators with no meaning section

mathics/builtin/datentime.py, mathics/core/evaluation.py, mathics/eval/sympy.py, pyproject.toml
If this works, maybe we can simplify the implementation of `TimeConstrained
=> use stopit to implement TimeConstrained

mathics/__init__.py, mathics/builtin/system.py, mathics/docpipeline.py
This PR implements the `Breakpoint[]` functionality discussed in issue #1172.
With this implementation, it is possible to invoke a Python breakpoint from the mathics command line for debugging. Alternative debuggers can be loaded by setting the relevant Python environment variable `PYTHONBREAKPOINT`. 
Please feel free to edit the description text.
=> Implement `Breakpoint[]`

mathics/builtin/functional/apply_fns_to_lists.py, mathics/builtin/messages.py, mathics/builtin/string/operations.py, mathics/builtin/string/patterns.py, mathics/builtin/tensors.py, mathics/builtin/testing_expressions/equality_inequality.py, mathics/builtin/testing_expressions/logic.py, mathics/core/builtin.py
Set operator precedence for  no-meaning prefix and posftix operators
Remove some  `operator =`  assignments in some Operator classes so we use the operator symbols from JSON.
A lot more work is needed here. This is just the first step.
=> Another mini operator refactor

mathics/builtin/scoping.py, test/builtin/test_scoping.py
```mathematica
Block[{i = 0}, With[{}, Module[{j = i}, Set[i, i+1]; j]]]
```` 
returns `1` whereas the correct answer is `0`. This is because, `With` evaluates the `Module` expression but erroneously returns the unevaluated version, triggering a second evaluation.
The fix is to return the evaluated version. With the fix, the above code returns `0` as expected.
=> Bugfix in `With`: Return evaluated result

mathics/builtin/files_io/files.py, mathics/core/streams.py, mathics/eval/files_io/read.py, test/builtin/files_io/test_files.py
We need to lookup streams opened by the name or string the gives, not the resolved path name. 
This bug was discovered in trying to run Analytica.  <strike>At some point in the vague future, I'll write up a bug report, and possibly tidy this.</strike>
Fixes #1195
=> Lookup streams by user (short) names

mathics/builtin/distance/numeric.py, mathics/core/convert/python.py, mathics/eval/distance.py
Handle CosineDistance more correctly in symbolic computations that should use Conjugate. Code adapted from https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/builtin/ClusteringFunctions.java#L377-L386
However, we also add the situation where arguments are numeric scalars, and we check for mismatched vector lengths.
Some tweaking of code for conversion to/from Complex has been done. 
TODO: more tests. 
There is a bit more that could be done, but this is getting large already. 
Fixes #1197
=> Improve cosine distance

mathics/builtin/trace.py, test/builtin/test_exp_structure.py, test/builtin/test_trace.py
This should address the problem seen via Rubi testing where TraceEvalution was called and we hit a recursion limit.
See https://github.com/Mathics3/Mathics3-Rubi/pull/2#issuecomment-2515442000
=> Reset `TraceEvaluation[]` params on an exception

test/builtin/test_datentime.py
Disable 3-arg `TimeConstrained[]` test on macos
=> Disable 3-arg test on macos

mathics/builtin/distance/numeric.py, mathics/builtin/numeric.py, mathics/eval/distance/numeric.py, test/builtin/distance/test_numeric.py
Switch from using Python's multiply and divide, and abs() of complex numbers  to SymPy's Expr operators for more precise real-number results
=> Complex cosine distance

mathics/builtin/numbers/randomnumbers.py
Fixes #1221 
Before change: 
```
$ mathics -e 'Table[Random[], {6}]'
{{0.}, {0.}, {4.94066×10^-324}, {0.}, {0.}, {0.}}
```
After change: 
```
mathics -e 'Table[Random[], {6}]'
{0.0480615, 0.0366987, 0.0705173, 0.283725, 0.84478, 0.138017}
```
Rule rewrites before change: 
```
In[4]:= TraceEvaluation[Random[]]
Evaluating: System`Random[]
Evaluating: System`Random
-> System`RandomReal[0, 1]
Evaluating: System`RandomReal
-> System`RandomReal[System`List[0, 0], 1]
Evaluating: System`RandomReal
Evaluating: System`List[0, 0]
-> System`RandomReal[System`List[0, 0], System`List[1]]
Evaluating: System`RandomReal
Evaluating: System`List[0, 0]
Evaluating: System`List[1]
-> {5e-324}
Out[4]= {4.94066×10^-324}
```
=> Make Random[] more random

mathics/builtin/numbers/randomnumbers.py, mathics/packages/DiscreteMath/CombinatoricaV0.9.m, test/package/test_combinatorica.py
SetPartitions[]`  and `KSetPartitions[]` from Combinatorica workin V2.0 (In V.09 it is not broken, it is just altogether missing.)  
So copy the 2.0.0 code into V0.9
=> Combinatorica V0.9 workarounds and expanded tests

mathics/builtin/graphics.py, mathics/format/asy.py, mathics/format/svg.py, test/format/test_format.py
graphics.py: Reduce size on PointSize, Thickness, AbsoluteThickness
svg.py: reduced thickness of text in InsetBox
I have been looking at graphs in Implementing Discrete Mathematics and noticed for a while that dots shown in Mathics3  seem a bit too big compared to what they are in the text, and text for axes is too bold. 
Here is an attempt to make this look more like what is printed in this book. 
For comparison with change: examples of dot sizes: 
Before:
Proposed change:
And text in axes of graphs. Before: 
Proposed change: 
Since I don't have access to anything that draws corresponding Mathematica graphs I rely on you to let me know if this is closer.
Note this is not about whether one is aesthetically better than the other, but instead, whether this matches what Mathematica does. The …
=> Adjust sizes and text to match Mathematica better?

mathics/builtin/messages.py, mathics/core/evaluation.py
Sort error message strings and add `stresc`.
Also, in the scanner "sntoct{1,2} do not provide a file/line combination
=> Sort error message strings and add stresc

mathics/builtin/box/graphics.py, mathics/builtin/drawing/graphics_internals.py, mathics/builtin/graphics.py, mathics/format/svg.py, test/format/test_svg.py
graphics.py:
* Reduce default asy line width
* Add a return type annotation
* remove deprecated logging.warn
asy.py:
* Remove math mode in text label
svg.py
* Remove deprecated version number in <svg> tag.
* Convert to format strings
=> More changes to Graphics (part2)

mathics/builtin/box/graphics.py, mathics/format/asy.py, mathics/format/svg.py
Add the notion of text alignment of InsetBox which is typically used in drawing axes. The text for an x (horizontal) axis is under the ticks while the text for a y (vertical) axis is to the left.
Here we've done this for asymptote and SVG. There is a lot more that could be done, but this is a small start.
=> Start adding Alignment to InsetBox in 2D graphs

mathics/__init__.py, mathics/builtin/scoping.py, mathics/builtin/system.py, mathics/core/definitions.py, mathics/eval/scoping.py, pyproject.toml
the `Contexts[string]` form is used by Mathics3 package ``Utilities`CleanSlate``
=> Add Contexts[string] form

.github/workflows/packages.yml
This draft is not really for merging but for testing that if we merge https://github.com/Mathics3/Mathics3-Combinatorica/pull/5, then we won't break Mathics-core. 
After Combinatorica is changed, we would then change the  "package.yml" file of this draft to pull from "master" rather than a branch.
=> Track Combinatorica v201 and v091

.github/workflows/packages.yml, mathics/core/expression.py, mathics/eval/drawing/plot.py, test/helper.py
The good stuff from #1245, but alas the thing we were trying to do there can cause an infinite loop in the eval_ListPlot routine. So let's do this part and narrow that PR.
=> Lint found in ListPlot-point checking branch

.github/workflows/macos.yml, .github/workflows/mypy.yml, .github/workflows/packages.yml, .github/workflows/pyodide.yml, .github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, mathics/builtin/arithfns/basic.py, mathics/builtin/assignments/assign_binaryop.py, mathics/builtin/assignments/assignment.py, mathics/builtin/assignments/clear.py, mathics/builtin/exp_structure/general.py, mathics/builtin/patterns/composite.py, mathics/builtin/patterns/rules.py, mathics/core/builtin.py, mathics/core/convert/op.py, mathics/core/evaluation.py
Pick up binary operator string from enhanced Mathics-Scanner JSON operator tables. 
For now, we have to limit to binary operators only.
=> Increased use of binary operator string values from JSON

mathics/builtin/assignments/assign_binaryop.py, mathics/builtin/atomic/symbols.py, mathics/builtin/files_io/files.py, mathics/builtin/functional/application.py, mathics/builtin/functional/apply_fns_to_lists.py, mathics/builtin/layout.py, mathics/builtin/list/eol.py, mathics/builtin/messages.py, mathics/builtin/no_meaning/infix_extra.py, mathics/builtin/numbers/calculus.py, mathics/builtin/patterns/composite.py, mathics/builtin/patterns/defaults.py, mathics/builtin/patterns/restrictions.py, mathics/builtin/patterns/rules.py, mathics/builtin/procedural.py, mathics/builtin/specialfns/gamma.py, mathics/builtin/testing_expressions/logic.py, mathics/core/builtin.py
Remove hard-coded operator precedences and pull from YAML tables from scanner project (via JSON).
=> More Unary and Binary operators from JSON

mathics/builtin/assignments/assignment.py, mathics/builtin/atomic/symbols.py, mathics/builtin/evaluation.py, mathics/builtin/list/constructing.py, mathics/builtin/scoping.py, mathics/core/assignment.py, mathics/core/convert/regex.py, mathics/core/definitions.py, mathics/core/rules.py, mathics/doc/doc_entries.py, mathics/doc/online.py, mathics/eval/assignments/__init__.py, mathics/eval/assignments/assignment.py, mathics/main.py
This PR changes the way in which  `Definitions.get_definition` and `Definitions.get_user_definition` report that a `Definition` object is not available for a given symbol name, by raising an exception instead of returning `None`. This helps to avoid recasts in static type analysis.
=> Removing the  to the return value in Definitions.get_definition

mathics/builtin/messages.py, mathics/builtin/options.py, mathics/core/definitions.py, mathics/core/evaluation.py, mathics/core/expression.py, mathics/eval/nevaluator.py, mathics/eval/patterns.py, mathics/session.py
This completes the task of adding type annotations to all the methods in the mathics.core.definition module. Also, changes the behavior of `Definition.get_*` methods, to avoid the use of Optional[...] return values.
=> More type consistency in mathics.core.definitions

CHANGES.rst, mathics/builtin/makeboxes.py, mathics/core/builtin.py, mathics/core/definitions.py, mathics/core/element.py, mathics/core/pattern.py, mathics/core/rules.py, mathics/doc/online.py, mathics/eval/assignments/assignment.py, mathics/main.py
Investigating the causes of https://github.com/Mathics3/mathicsscript/issues/87#issue-2777113442 I discover that
we were not consistent in the use of `Definitions.get_ownvalue`. This PR tries to amend this.
=> Improve get_ownvalue. Narrower type annotations.

mathics/builtin/files_io/files.py, mathics/core/streams.py, mathics/eval/files_io/files.py
Also, move code to class to eval_Close under `mathics.eval`
We mimic WMA behavior which is slightly different from what the docs say it should do when closing duplicate open streams by name.
=> Add Close["path"]

mathics/builtin/drawing/graphics3d.py, mathics/builtin/forms/other.py, mathics/builtin/no_meaning/infix_extra.py, mathics/builtin/numbers/numbertheory.py, mathics/builtin/testing_expressions/equality_inequality.py, mathics/core/convert/op.py, mathics/doc/latex/sed-hack.sh, mathics/doc/latex_doc.py, mathics/docpipeline.py, mathics/format/latex.py, test/builtin/drawing/test_plot.py, test/format/test_format.py, test/format/test_latex.py
Improving TeXForm to use name_character tables. Adjustments in docstrings.
DRY get_latex_operator. More adjustments
=> Fixing Latex documentation.

CHANGES.rst, mathics/builtin/arithfns/basic.py, mathics/builtin/atomic/strings.py, mathics/builtin/atomic/symbols.py, mathics/builtin/distance/clusters.py, mathics/builtin/list/eol.py, mathics/builtin/string/operations.py, mathics/builtin/trace.py, mathics/core/builtin.py, mathics/core/rules.py
This is one tiny change I wanted to implement for a while. Im WMA, if you want to implement a rule that returns the same expression if certain test fails, the way to do it is
```
expression: Half[expr]:=If[NumberQ[expr], expr/2, expression]
```
i.e. use a `Pattern[patname, pat]` expression to pass the whole original unevaluated expression (`Half[a]` in the example) to the replace expression. However, we could not do this in the patterns especified in docstrings, because we "overloaded" the meaning of `patname: pattern` in the function that loads `eval_*` and `format_*` methods: we use them to indicate in the case of `format_` methods to which `Format` corresponds the rule. 
As in some methods we need the full original expression, then we added a "hack" to interpret a parameter …
=> Improve get functions for patterns

.gitmodules, mathics/Packages/Rubi.wl
This now works for me. 
To get tests to run, I have to give the full path name on `SanityCheck.m` inside `TestRubi`. But it's a start.
=> Rubi submodule again

mathics/builtin/arithmetic.py, mathics/builtin/files_io/importexport.py, mathics/builtin/functional/apply_fns_to_lists.py, mathics/builtin/testing_expressions/equality_inequality.py, mathics/builtin/trace.py, mathics/core/builtin.py, mathics/doc/documentation/1-Manual.mdoc, mathics/doc/latex/Makefile
First part of an unknown number of rounds of documentation review.
=> Doc updates

mathics/core/builtin.py, test/core/test_builtin.py
Some missing details that I discovered regarding these methods, and a pytest to test the right behaviour:
* Fix the regular expression used in get_function to support multiline docstrings.
* Fix how the full name of builtins are built in `contribute`  when the class does not have a `context` attribute.
* Add tests for Builtin.contribute
More tests can be added later.
=> More on Builtin.contribute and Builtin.get_functions.

test/builtin/test_datentime.py
Some of the `TimeConstrained[]` tests do not work if we have the last PyPI distributed stopit.
=> Limit TimeConstrained tests if unpatched stopit

CHANGES.rst, mathics/builtin/atomic/symbols.py, mathics/core/assignment.py
This PR adds `FormatValues` to access the format values of Symbols.
=> FormatValues

CHANGES.rst, mathics/builtin/arithfns/basic.py, mathics/builtin/assignments/assign_binaryop.py, mathics/builtin/directories/system_directories.py, mathics/builtin/files_io/filesystem.py, mathics/builtin/list/associations.py, mathics/builtin/numbers/calculus.py, mathics/builtin/numbers/integer.py, mathics/builtin/numbers/numbertheory.py, mathics/builtin/numeric.py, mathics/builtin/statistics/orderstats.py, mathics/builtin/system.py
* Go over summaries
* Go over  `PowersRepresentation` and `ReverseSort`
=> Doc updates part6

mathics/builtin/colors/named_colors.py, mathics/builtin/directories/user_directories.py, mathics/builtin/distance/numeric.py, mathics/builtin/graphics.py, mathics/builtin/intfns/combinatorial.py, mathics/builtin/numbers/calculus.py, mathics/builtin/numbers/linalg.py, mathics/builtin/numbers/numbertheory.py, mathics/builtin/specialfns/gamma.py, mathics/builtin/string/patterns.py
Subfactorial is not a mpmath function, SymPy only. SymPy can't handle machine reals that are not integers. Add rule to handle lists. 
Various summaries have been gone over to have them start with an active verb when possible.
=> Doc updates part7

mathics/settings.py
On my workstation $HOME/.local/var did not exist, and mathics failed with this error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/thierry/.local/var/Mathics3/'
This simple one-liner create USER_PACKAGE_DIR if necessary.
=> mathics/settings.py: create USER_PACKAGE_DIR with its parents

mathics/core/builtin.py
`Builtin.get_functions` collects attributes of the subclasses with names starting with a prefix, and assumes that are methods. Until now, the way to check that are indeed methods was to check if they have a docstring. This is not completely correct (because what we want to check is if the method is callable) and since Python 3.13 it breaks the mechanism.
This PR implements the right check.
=> Reinforce in get_functions that eval/format methods are indeed callable

CHANGES.rst, mathics/main.py
In the WMA CLI, when an expression evaluates to ```System`Null```, there is no `Out[]=...` line. This PR reproduces this behavior.
=> not show Out[]=Null as in wolframscript

mathics/builtin/files_io/filesystem.py, mathics/builtin/files_io/importexport.py
Now that we have more `mathics.eval`  `eval_...`  functions, there are a probably a lot more opportunities like this one involving `Close()`.  
While I am not a fan of petty optimization, `eval_Close(...)` is simpler and clearer than `Expression(SymbolClose, ...).evaluate(...)`
And if you are tracing Evaluations, calling `Expression()`  as historically done, also pollutes tracing, along with its inherent slowness and complication. 
If you _do_ want see see the close() calls, you can always trace the `mathics.eval`  `eval_xxx` functions.
=> use eval_Close, and some fs lint

mathics/builtin/drawing/uniform_polyhedra.py, mathics/builtin/quantum_mechanics/angular.py, mathics/doc/doc_entries.py, mathics/doc/documentation/1-Manual.mdoc, mathics/doc/latex/1-Manual.mdoc, mathics/doc/latex/Makefile, mathics/doc/latex_doc.py
Among other hacks, the homebrew documentation system introduces some *custom* tags, that make the parsing process unnecessarily complex. A couple of them are `<CONSOLE>content</CONSOLE>` and `<CON>content</CON>`. Both means more or less the same as using `'content'`.
This PR removes the second form, with the idea of removing the first form too, in favor of using '``' or  
```'.. code-block:: console```, following markdown or ReStructuredText conventions.
Also, `mathics/doc/latex/1-Manual.mdoc` was removed, which is just a copy of `mathics/doc/documentation/1-Manual.mdoc`
=> removing <CON>...</CON> in favor of <CONSOLE>...</CONSOLE> and single quote codemarks

MANIFEST.in, pyproject.toml
Adding all of the files and build system is a lot more involved. But we can at least add the pdf.
=> Add mathics.pdf to wheel and tarball

mathics/builtin/list/rearrange.py, test/builtin/list/test_list.py
Union, Complement and Intersection allow a SameTest option. This has to be matched not as a general options association, but instead as a SameTest association
=> Bug: an association was confused with an option

mathics/autoload/formats/Asy/Export.m, mathics/builtin/binary/io.py, mathics/builtin/files_io/importexport.py, test/builtin/test_binary.py
These items were noticed in looking at what is needed to support some version of PacletManager.  After this there set of changes, there will be more changes to put more Import code, BinaryRead, into `mathics.eval` and to handle `BinaryReadList` which is needed to be able to support Importing gzip files.
=> Small lint-like changes to BinaryRead and Import

mathics/builtin/files_io/files.py, mathics/builtin/files_io/importexport.py, mathics/eval/files_io/files.py, mathics/eval/files_io/read.py
Isolate a file open evaluation routine used by `Import`, `OpenRead`, and `OpenWrite`.
=> Split out eval_Open to mathics.eval.files

mathics/builtin/arithmetic.py, mathics/builtin/no_meaning/infix.py, mathics/builtin/specialfns/gamma.py, mathics/core/builtin.py
Go over docs for `Beta`, `Gamma`,  `Product`, and infix operators with no meaning
=> Go over docs for gamma and no-meaning infix ops

.gitignore, mathics/builtin/arithmetic.py, mathics/builtin/specialfns/gamma.py, test/builtin/specialfns/test_gamma.py
We want to match the behavior of WMA for `Gamma` and `Product`. Specifically: 
```
Product[k, {k, 3, n}] == n! / 2
Gamma[1+x] == Gamma[1+x]
```
Supercedes #1387
=> Match WMA for Gamma[1+x] and Product[...]

mathics/core/assignment.py, mathics/core/builtin.py, mathics/core/convert/expression.py, mathics/core/evaluation.py, mathics/core/expression.py, mathics/core/list.py, mathics/core/load_builtin.py, mathics/core/rules.py, mathics/core/structure.py, mathics/core/symbols.py
found with the help of `sage --tox -e rst -- mathics/core`
=> some fixes for rst syntax in core/

mathics/builtin/atomic/numbers.py, mathics/builtin/atomic/strings.py, mathics/builtin/box/graphics.py, mathics/builtin/box/graphics3d.py, mathics/builtin/datentime.py, mathics/builtin/drawing/plot.py, mathics/builtin/files_io/files.py, mathics/builtin/intfns/divlike.py, mathics/builtin/numbers/hyperbolic.py, mathics/builtin/numbers/numbertheory.py, mathics/builtin/optimization.py, mathics/builtin/specialfns/gamma.py, mathics/builtin/specialfns/orthogonal.py, mathics/builtin/string/operations.py, mathics/core/expression.py, mathics/doc/structure.py, mathics/eval/arithfns/basic.py, mathics/format/asy_fns.py
just fixing a few more typos
and also the lines `variable = variable` that were in 4 files
=> more typos fixed and no self-assignment

.github/workflows/consistency-checks.yml, .github/workflows/macos.yml, .github/workflows/mypy.yml, .github/workflows/packages.yml, .github/workflows/pyodide.yml, .github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, CHANGES.rst, mathics/builtin/atomic/strings.py, mathics/builtin/testing_expressions/string_tests.py, mathics/core/evaluation.py, mathics/core/parser/parser.py, mathics/core/parser/util.py, mathics/eval/files_io/files.py, test/core/parser/test_convert.py, test/core/parser/test_parser.py, test/core/parser/test_util.py
Tracks changes in scanner to handle escape sequences more correctly and to handle escaped boxing operators more properly. 
* .github/workflows: CI testing needs to be done with revise-escape-sequence-scanning branch
* parser.py: next() needs to catch at least escape sequence errors. (Maybe more?)
* test_parser.py: we now give a more specific "NamedCharacterSyntaxError" error
Comment out self.check("x \\\ny", "Times[x, y]") test until we understand what the right behavior is. (Next time we'll document the test better.)
=> Adjustments for escape-sequence scanning changes

mathics/core/expression.py
Use {} instead of None for inital structure cache
Fixes #1405
=> Address bug in structure cache `None `accessed as a `dict`

mathics/eval/tracing.py
Add skip_trivial_evaluation. This is also used in the Mathics Debugger to not stop too many at places that are not of interest. (evaluating a literal string, or a Symbol, etc.)
=> Split out fn from print_evaluate

mathics/eval/tracing.py, test/builtin/test_trace.py
When tracing an evaluation, allow the wrapper function to replace or alter the function retutn value.
This is used in the Trepan DebugEvaluate debugger, but it can be used by other tracing tools as well.
=> Adjust trace API to be able to set expr values

.github/workflows/consistency-checks.yml, .github/workflows/isort-and-black-checks.yml, .github/workflows/macos.yml, .github/workflows/mypy.yml, .github/workflows/packages.yml, .github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
Use Python version 3.13 in testing. It's faster
=> Use solely or include 3.13 testing

mathics/builtin/datentime.py, mathics/builtin/directories/directory_names.py, mathics/builtin/file_operations/file_properties.py, mathics/builtin/files_io/files.py, mathics/builtin/files_io/filesystem.py, mathics/builtin/forms/output.py, mathics/builtin/list/rearrange.py, mathics/builtin/numbers/numbertheory.py, mathics/builtin/numbers/randomnumbers.py, mathics/core/atoms.py, mathics/core/convert/expression.py, mathics/core/element.py, mathics/core/expression.py, mathics/core/list.py, mathics/core/streams.py, mathics/eval/drawing/plot.py, mathics/eval/drawing/plot3d.py, mathics/eval/files_io/read.py, test/builtin/files_io/test_files.py, test/core/test_sympy_python_convert.py, test/test_to_python.py
Make use of the  ".value" field in BaseElement objects, especially  Expression.to_python(). 
Recall, the parser creates Python equivalents for certain literal values. In particular, a list of strings. For this, a Python tuple of `str` appears. And this kind of thing happens a lot.  And note that in contrast to Mathics3 strings, a Python string can be duplicated. So by using `.value` of strings found in parsing, we are not only saving time in creation by not copying, but also memory. And we save time in `to_python()` access as well. In some cases, like datetime objects, we can just skip `to_python()`  and use `.value` instead.
This motivation for this came from a desire to do a similar thing for SymPy and NumPy expressions, but that will have to wait. 
In the parser, list element literals …
=> Use ".value" in expr.to_python() and more often

.github/workflows/consistency-checks.yml, .github/workflows/macos.yml, .github/workflows/mypy.yml, .github/workflows/packages.yml, .github/workflows/pyodide.yml, .github/workflows/ubuntu-cython.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, mathics/builtin/tensors.py, mathics/core/convert/matrix.py, mathics/core/convert/sympy.py, mathics/core/rules.py, mathics/eval/tensors.py
Expand `Transpose[]` and add  SymPy  conversion to SymPy `Array`
Transpose can now handle 3-dimensional (and 0-dimensional and 1-dimensional) tensors.
Make use of  `.value` on list literals when converting to SymPy.
Fixes #1412
=> Revise transpose

mathics/main.py, test/test_main.py, test/test_returncode.py
Make CLI options more like wolframscript. This is an incompatible change. Single-dash long options like ``-help``, ``-file``
are now accepted. Short option ``-f`` is associated with ``-file`` rather than ``--fullform``; ``-F`` is is now used for Fullform.
Option ``--read`` with alias ``-r`` is now ``-code`` and short option `-c`.
=> Make `mathics` CLI options more like wolframscript

mathics/builtin/files_io/files.py, mathics/eval/stackframe.py
Introduce `get_eval_Expression()`
`get_eval_Expression()` can be used in Mathics3 Builtin evaluation methods to find the Expression that caused the evaluation to get triggered.
mathics.file_io.files module converted to use this function to test worthiness.
=> Add get_eval_Expression()

Makefile, mathics/builtin/atomic/numbers.py, mathics/builtin/files_io/files.py, test/builtin/patterns/test_rules.py
Remove two builtin eval-methods that existed only to issue some errors.
Instead, the tests which are parameter type checks, have been folded into the broader evaluation method for that builtin.
Also, add Makefile target `pytest-x` option to stop on first pytest failure. 
Add a ReduceList pytest.
=> remove some error checking-only eval methods and two small tweaks

mathics/builtin/evaluation.py, mathics/builtin/numbers/calculus.py, mathics/core/evaluation.py, mathics/core/symbols.py, mathics/session.py, test/builtin/test_attributes.py, test/builtin/test_evaluation.py
Fixes #1476
There are probably more places where we need to do something similar, but this is a start.
=> respect $IterationLimit more places

mathics/builtin/trace.py, mathics/doc/latex/mathics.tex
This PR changes `TracePrint` to show the result through the  `Print[]` interface. This allows us to show the result in the browser/CLI/docpipeline instead of the (raw) terminal.  
This is how it looks in the PDF documentation:
and this is how it looks in Mathics-Django help
=> Improve traceprint

mathics/eval/tracing.py
Lines of the form:
Replacing: x -> x
don't add much, so remove them.
In the future, maybe we can have a "verbosity level" to include something like this. The only purpose I can see is to indicate that a rewrite rule was considered and did nothing. However, TraceEvaluations are typically very long and, in my experience, don't add clarity, just clutter.
=> Shorten TraceEvaluation

mathics/builtin/atomic/symbols.py, test/builtin/atomic/test_symbols.py, test/test_help.py
This PR is one step towards improving the compatibility of the symbol `Information` between Mathics and Mathematica >=12.0.
Since the first implementation of the Builtin associated with this symbol (I guess, my first contribution to the project, circa 2013) and now, the way in which WMA implements this symbol has changed a lot.
Until WMA 11., `Information[symb_, LongForm->longform_]`  does not have an evaluation rule, just a format rule. The format rule printed some information about  `symb`, and return `Null` (like `Print`). The `LongForm` option controled if user defined rules where shown or not.
Since WMA 12., `Information[symb_, LongForm->longform_]` now is evaluated to an `InformationData[..]`, expression, which at the time, has format rules producing the output that we can see when …
=> improve Information

mathics/builtin/numbers/calculus.py, mathics/eval/numbers/calculus/optimizers.py
This PR improves the compatibility of `FindRoot`,`FindMinimum` and `FindMaximum`, by changing the behavior when the convergence is not achieved up to the requested tolerance. As in WMA, now the return value is the best candidate for the solution, even if the convergence fails.
=> Find* now returns the best value found after a convergency error.

mathics/builtin/numbers/calculus.py, mathics/core/convert/sympy.py, pyproject.toml, test/builtin/numbers/test_calculus.py, test/builtin/test-optimization.py
Allow Sympy 1.14 and greater. 
Also, separate `mathics.builtin.optimization` tests out of calculus testing.
See also: Issue #1498.
=> Allow SymPy 1.14 and greater
